In [47]:
import google_play_scraper
print("Library imported")

Library imported

In [49]:
from google_play_scraper import app

In [3]:
appId= "com.pubg.imobile"

In [4]:
resp = app("com.pubg.imobile" , lang = "en" , country = "in")

In [5]:
resp

{'title': 'BGMI: Online Multiplayer Game',
 'description': '[WHAT’S NEW]\r\n\r\nHello BGMI Fans!\r\n\r\nTrying out BGMI for the first time? Worry not! Dive into the ultimate multiplayer game experience with amazing rewards, expert training sessions, epic suits, and an all-new ride. Ready to prove your skills? Let’s go!\r\n\r\n[Spooky Soiree Theme Mode]\r\nWelcome to Spooky Soiree Theme Mode – the Ultimate Action Game Adventure!  Unleash the legendary power of ghosts in the Battlegrounds and experience epic action like never before! Ride into battle in style with the broom, gliding through chaos with unmatched speed and flair.\r\nNo matter how you choose to fight, every moment promises adrenaline-packed action in the BATTLEGROUNDS. This is the battle royale experience you’ve been waiting for!\r\n\r\n[Play & Win – Epic Rewards in the Ultimate Action Online Game!]\r\nComplete your favorite missions in BGMI, the most thrilling multiplayer action game, and win epic in-game rewards! Explore world castles in the battle royale mode, claim exclusive rewards for every challenge. Test your skills in the ultimate online shooting game.\r\n\r\n[MAX OUT & SHOW OFF: The Ultimate Suit Collection is Here!]\r\nGet ready to dominate the BATTLEGROUNDS in style with the arrival of the new Suits and the legendary gun skins. These aren’t just outfits—they’re a symbol of power, prestige, and unmatched dominance.\r\n\r\n[UC Up – Get Up to 100% UC! - Action games have never been this rewarding!] \r\nLooking to upgrade? This is your chance! Load up on UC and grab amazing deals. Get up to 100% UC. Check the events section for your next big upgrade. Power up your shooting game and rule the BATTLEGROUNDS!\r\n\r\n[Wear Your Cred – Royale Pass A15 is Here!]\r\nStep into the ultimate multiplayer action game with new Royale Pass A15! Unlock the exclusive Sets and earn stylish rewards at every level. Get your UC back as you level up. This is your chance to customize your gaming experience in one of the best online action games!\r\n\r\nJump Into BGMI – The Ultimate Online Multiplayer Game!\r\n\r\nBrace yourself for fast-paced, action-packed events in the biggest battle royale and shooting game. Whether you’re a novice or a pro, the path to becoming a BATTLEGROUNDS champion starts here!\r\n\r\nWhy wait? Jump into BGMI, the ultimate online multiplayer game, and show your squad skills today!\r\n\r\nFollow us on \r\nOfficial Website: www.battlegroundsmobileindia.com\r\nYouTube: https://www.youtube.com/c/BattlegroundsMobile_IN/\r\nInstagram: https://www.instagram.com/battlegroundsmobilein_official/',
 'descriptionHTML': '[WHAT’S NEW]<br><br>Hello BGMI Fans!<br><br>Trying out BGMI for the first time? Worry not! Dive into the ultimate multiplayer game experience with amazing rewards, expert training sessions, epic suits, and an all-new ride. Ready to prove your skills? Let’s go!<br><br>[Spooky Soiree Theme Mode]<br>Welcome to Spooky Soiree Theme Mode – the Ultimate Action Game Adventure!  Unleash the legendary power of ghosts in the Battlegrounds and experience epic action like never before! Ride into battle in style with the broom, gliding through chaos with unmatched speed and flair.<br>No matter how you choose to fight, every moment promises adrenaline-packed action in the BATTLEGROUNDS. This is the battle royale experience you’ve been waiting for!<br><br>[Play &amp; Win – Epic Rewards in the Ultimate Action Online Game!]<br>Complete your favorite missions in BGMI, the most thrilling multiplayer action game, and win epic in-game rewards! Explore world castles in the battle royale mode, claim exclusive rewards for every challenge. Test your skills in the ultimate online shooting game.<br><br>[MAX OUT &amp; SHOW OFF: The Ultimate Suit Collection is Here!]<br>Get ready to dominate the BATTLEGROUNDS in style with the arrival of the new Suits and the legendary gun skins. These aren’t just outfits—they’re a symbol of power, prestige, and unmatched dominance.<br><br>[UC Up – Get Up to 100% UC! - Action games have never been this rewarding!] <br>Looking to upgrade? This is your chance! Load up on UC and grab amazing deals. Get up to 100% UC. Check the events section for your next big upgrade. Power up your shooting game and rule the BATTLEGROUNDS!<br><br>[Wear Your Cred – Royale Pass A15 is Here!]<br>Step into the ultimate multiplayer action game with new Royale Pass A15! Unlock the exclusive Sets and earn stylish rewards at every level. Get your UC back as you level up. This is your chance to customize your gaming experience in one of the best online action games!<br><br>Jump Into BGMI – The Ultimate Online Multiplayer Game!<br><br>Brace yourself for fast-paced, action-packed events in the biggest battle royale and shooting game. Whether you’re a novice or a pro, the path to becoming a BATTLEGROUNDS champion starts here!<br><br>Why wait? Jump into BGMI, the ultimate online multiplayer game, and show your squad skills today!<br><br>Follow us on <br>Official Website: www.battlegroundsmobileindia.com<br>YouTube: https://www.youtube.com/c/BattlegroundsMobile_IN/<br>Instagram: https://www.instagram.com/battlegroundsmobilein_official/',
 'summary': 'Enter Ghost Mode: summon spirits, haunt enemies, and claim victory in BGMI!',
 'installs': '100,000,000+',
 'minInstalls': 100000000,
 'realInstalls': 216701795,
 'score': 4.1702566,
 'ratings': 6972876,
 'reviews': 2409841,
 'histogram': [1152973, 140139, 188169, 377041, 5114549],
 'price': 0,
 'free': True,
 'currency': 'INR',
 'sale': False,
 'saleTime': None,
 'originalPrice': None,
 'saleText': None,
 'offersIAP': True,
 'inAppProductPrice': '₹6.25 - ₹12,600.00 per item',
 'developer': 'KRAFTON, Inc.',
 'developerId': '4685442390253494069',
 'developerEmail': 'battlegroundsindia_support@krafton.com',
 'developerWebsite': 'https://www.Battlegroundsmobileindia.com',
 'developerAddress': None,
 'privacyPolicy': 'https://www.battlegroundsmobileindia.com/privacy',
 'genre': 'Action',
 'genreId': 'GAME_ACTION',
 'categories': [{'name': 'Action', 'id': 'GAME_ACTION'},
  {'name': 'Shooter', 'id': None},
  {'name': 'Tactical shooter', 'id': None},
  {'name': 'Multiplayer', 'id': None},
  {'name': 'Competitive multiplayer', 'id': None},
  {'name': 'Single player', 'id': None},
  {'name': 'Realistic', 'id': None},
  {'name': 'Competitive', 'id': None},
  {'name': 'Modern', 'id': None},
  {'name': 'Military', 'id': None}],
 'icon': 'https://play-lh.googleusercontent.com/KieTROLwzhE25mwyHBAvH9MrxynZm3DIeGwuZKBarh4kVLoiRakxr2v7yZ0TwUmdulKN3eopWKThrdos2JaEoQ',
 'headerImage': 'https://play-lh.googleusercontent.com/oABUQ7aetcrVneg3zIPa7nADVjLvzyDBkfDqPavAA4MpAnxQaEbXhOjnqiP4DKUuu8WEYaY5LkJL3mL8Lukljw',
 'screenshots': ['https://play-lh.googleusercontent.com/2tBfkdrk_wveNlijaUSJXbDpr17Tus8-V8OCytRM52wgpB_vV0GxePPGNXMwoN7I1SYclKApOttC9_OGhYqhXdA',
  'https://play-lh.googleusercontent.com/lNRmFn51tGGYM29EmeQxCLAjbHOnyUjoMhGlXRlFhGhj-OHwDIuSPVJvWmPPF-EOg7QMfBSnZVVot4Sn0zdmdQ',
  'https://play-lh.googleusercontent.com/QWViItX0zh38JVZ56gEmgEDInxhSjDLs7XzrJWOgm3VvUJbldqHU2j6j_6lsrUQmWWoja4SE0zb3yrTA_zIddYA',
  'https://play-lh.googleusercontent.com/a-t4uaiQzhjaqNJWBIHE3uYI7RUSuaeQ5xRXVDAsm6hg_z-UVskLaIpsm-nSD0yJPwcX5CjB4YzGZkXAnlTheWc',
  'https://play-lh.googleusercontent.com/ho-6qPHEZ6l8czm4ZWLQ8XQQoQytt_qKK4_LcYID6OuS8GWSXWe1B1UwnEW1ZHcWh-VyA-mXQQWE7vXclgxd8Ao',
  'https://play-lh.googleusercontent.com/r-FJ10GAcnerw2f_pOD1GQ3J2nQLXwoFmppBrkwoGiYMbpAox-h9l3FtkZHHtrAFjC4FGP6kUUPYc9eXkyEHMw',
  'https://play-lh.googleusercontent.com/XIlCI-orsjbAyUeN_PDvr_lfbo8koPCylpyVWLnmyrDVbD9rFfend4AEKCA7uo0kFH28auK93oH_TuWYJuR1FA',
  'https://play-lh.googleusercontent.com/qy0RFNlV0PoUHTI0WGz0MQyll3Y81xbmKNy8xQkoP8aAa1JM5dmJO9f23rNoXuXCG9w',
  'https://play-lh.googleusercontent.com/2tBfkdrk_wveNlijaUSJXbDpr17Tus8-V8OCytRM52wgpB_vV0GxePPGNXMwoN7I1SYclKApOttC9_OGhYqhXdA',
  'https://play-lh.googleusercontent.com/lNRmFn51tGGYM29EmeQxCLAjbHOnyUjoMhGlXRlFhGhj-OHwDIuSPVJvWmPPF-EOg7QMfBSnZVVot4Sn0zdmdQ',
  'https://play-lh.googleusercontent.com/QWViItX0zh38JVZ56gEmgEDInxhSjDLs7XzrJWOgm3VvUJbldqHU2j6j_6lsrUQmWWoja4SE0zb3yrTA_zIddYA',
  'https://play-lh.googleusercontent.com/a-t4uaiQzhjaqNJWBIHE3uYI7RUSuaeQ5xRXVDAsm6hg_z-UVskLaIpsm-nSD0yJPwcX5CjB4YzGZkXAnlTheWc',
  'https://play-lh.googleusercontent.com/ho-6qPHEZ6l8czm4ZWLQ8XQQoQytt_qKK4_LcYID6OuS8GWSXWe1B1UwnEW1ZHcWh-VyA-mXQQWE7vXclgxd8Ao',
  'https://play-lh.googleusercontent.com/r-FJ10GAcnerw2f_pOD1GQ3J2nQLXwoFmppBrkwoGiYMbpAox-h9l3FtkZHHtrAFjC4FGP6kUUPYc9eXkyEHMw',
  'https://play-lh.googleusercontent.com/XIlCI-orsjbAyUeN_PDvr_lfbo8koPCylpyVWLnmyrDVbD9rFfend4AEKCA7uo0kFH28auK93oH_TuWYJuR1FA',
  'https://play-lh.googleusercontent.com/SjHuoGgukqVTNl2-Bj_PKZAhvThAss_esf-h3PLcsr4hRUyM5CfCo_eRCJn5D1_19g',
  'https://play-lh.googleusercontent.com/2tBfkdrk_wveNlijaUSJXbDpr17Tus8-V8OCytRM52wgpB_vV0GxePPGNXMwoN7I1SYclKApOttC9_OGhYqhXdA',
  'https://play-lh.googleusercontent.com/lNRmFn51tGGYM29EmeQxCLAjbHOnyUjoMhGlXRlFhGhj-OHwDIuSPVJvWmPPF-EOg7QMfBSnZVVot4Sn0zdmdQ',
  'https://play-lh.googleusercontent.com/QWViItX0zh38JVZ56gEmgEDInxhSjDLs7XzrJWOgm3VvUJbldqHU2j6j_6lsrUQmWWoja4SE0zb3yrTA_zIddYA',
  'https://play-lh.googleusercontent.com/a-t4uaiQzhjaqNJWBIHE3uYI7RUSuaeQ5xRXVDAsm6hg_z-UVskLaIpsm-nSD0yJPwcX5CjB4YzGZkXAnlTheWc',
  'https://play-lh.googleusercontent.com/ho-6qPHEZ6l8czm4ZWLQ8XQQoQytt_qKK4_LcYID6OuS8GWSXWe1B1UwnEW1ZHcWh-VyA-mXQQWE7vXclgxd8Ao',
  'https://play-lh.googleusercontent.com/r-FJ10GAcnerw2f_pOD1GQ3J2nQLXwoFmppBrkwoGiYMbpAox-h9l3FtkZHHtrAFjC4FGP6kUUPYc9eXkyEHMw',
  'https://play-lh.googleusercontent.com/XIlCI-orsjbAyUeN_PDvr_lfbo8koPCylpyVWLnmyrDVbD9rFfend4AEKCA7uo0kFH28auK93oH_TuWYJuR1FA',
  'https://play-lh.googleusercontent.com/Ch3WJOKdmzahyofeYNrakMmOgoLUQFDpuZJXXJ_xHDhq47xQ6zPzsFvU0d8sk3N5Ig0'],
 'video': 'https://www.youtube.com/embed/Wqd_LMP379g?ps=play&vq=large&rel=0&autohide=1&showinfo=0',
 'videoImage': 'https://play-lh.googleusercontent.com/oABUQ7aetcrVneg3zIPa7nADVjLvzyDBkfDqPavAA4MpAnxQaEbXhOjnqiP4DKUuu8WEYaY5LkJL3mL8Lukljw',
 'contentRating': 'Rated for 16+',
 'contentRatingDescription': 'Strong Violence',
 'adSupported': True,
 'containsAds': True,
 'released': 'Jul 1, 2021',
 'lastUpdatedOn': 'Aug 26, 2025',
 'updated': 1756181585,
 'version': '4.0.0',
 'comments': [],
 'appId': 'com.pubg.imobile',
 'url': 'https://play.google.com/store/apps/details?id=com.pubg.imobile&hl=en&gl=in'}

In [6]:
resp.keys()

dict_keys(['title', 'description', 'descriptionHTML', 'summary', 'installs', 'minInstalls', 'realInstalls', 'score', 'ratings', 'reviews', 'histogram', 'price', 'free', 'currency', 'sale', 'saleTime', 'originalPrice', 'saleText', 'offersIAP', 'inAppProductPrice', 'developer', 'developerId', 'developerEmail', 'developerWebsite', 'developerAddress', 'privacyPolicy', 'genre', 'genreId', 'categories', 'icon', 'headerImage', 'screenshots', 'video', 'videoImage', 'contentRating', 'contentRatingDescription', 'adSupported', 'containsAds', 'released', 'lastUpdatedOn', 'updated', 'version', 'comments', 'appId', 'url'])

In [7]:
resp["title"]

'BGMI: Online Multiplayer Game'

In [8]:
resp["installs"]

'100,000,000+'

In [9]:
resp["score"]

4.1702566

In [10]:
resp["price"]

0

In [11]:
resp["url"]

'https://play.google.com/store/apps/details?id=com.pubg.imobile&hl=en&gl=in'

In [50]:
from google_play_scraper import search

In [13]:
games = search("Best car Games" , n_hits = 10 , lang = "en" , country = "in")

In [14]:
games

[{'appId': 'com.gameloft.android.ANMP.GloftA8HM',
  'icon': 'https://play-lh.googleusercontent.com/y1J3-OrqJIlezTtaung2sPOnHY9wS2hdJh26ADkwcc3kdZy4DTGyv94IN_YRvdKy0y4',
  'screenshots': ['https://play-lh.googleusercontent.com/dhOFRTswUhXAiuaiM1kf2uDbZXJ6UBw9iznSBSlRr79N_9TAPNUfiAKzhnEbeYs_-Eg',
   'https://play-lh.googleusercontent.com/4V6OyD55nW9YOgwF7xfjxf-0k1BuYtuP2oMW-CDUC9LbRGbTk4R-0BkbpL2qAsxFxAU',
   'https://play-lh.googleusercontent.com/F7scKYPJ-kIxs4LKdg6JBiWxBBYIQ8fs3SCHfQX81ClYB66086xW0N3-7cLxfvqnK0_h',
   'https://play-lh.googleusercontent.com/OGEPXlrlYSauDab7VXkLFzHJ70zqLawU2UVdAbMbTNY3IbD4IlA7ZbL1zRX7FG7nkQ',
   'https://play-lh.googleusercontent.com/JFDsqaLFEOlTWB-fvVDsMy1Hs_RCdtm1Mf1MAaZ8lIwgpLI_El6oBwfW1TeDIehZSnY',
   'https://play-lh.googleusercontent.com/-Ui4cPAOlx7KfO5jh3p_lDVPg7wuFt3wkP_tO1-4FcKxP3dWPvs5FYcjWHuy1BU5oYhW',
   'https://play-lh.googleusercontent.com/lhLqVqzBCXiweqbg616HdV1pvJjRbNnuEUitMmVqZgpx-Jez0ZiF4EVxe1dOqhU8vVo',
   'https://play-lh.googleusercontent.com/XmbMTgg87IQD1IaXGgy-_JJXrqAzsYPV3luZAK969shWd15TsW80skv-lgAs_9E5MW-n',
   'https://play-lh.googleusercontent.com/Y-0u2sg4wiC1dufvxAe-AeCIIYyGMsfDYiY_iN_wIr1c8XnmPV9DwtrSx5UqTq1BzHx5',
   'https://play-lh.googleusercontent.com/rU70n-GdavdTI_c2kx3WsIM9eWbddIuNe1V_T-Sc4Uzi65h7JSmMa8T5Ky5yWjmDk0g',
   'https://play-lh.googleusercontent.com/qnL8SW-mPVQpL7AMS4Vq9nOaKMgdvOXv7yxWPzIWgNnZ6EbWSnxNRpYgd94p7D_dRSPV',
   'https://play-lh.googleusercontent.com/rTWU9lp3sP0FgchIO8aqe1PckQ2wru8hzNTVpKPavtGFgUYHZK656iMkcVMI2zk0CtY',
   'https://play-lh.googleusercontent.com/qxwwW2vqgFvjxfwOfeZjD4VwRMsh6DMs0WoWeGDysBajxUCmfikp2-fEhC7MvKKOAdE',
   'https://play-lh.googleusercontent.com/8QNur3GMp6D5_duHn7YwmNJ4xcvTF4KtTmJZHJk9QpmdLpsRX0tLlq0B-iyI0Cm7CGU',
   'https://play-lh.googleusercontent.com/XAz0UtKmXpJjMIj617Z7ysW3rDGrnwjmDDcOzBRAoiERK0q3n841pnVM5qQIE_lE_cyd',
   'https://play-lh.googleusercontent.com/JAsu9UvB4w57u4-CWp4SHC-V5szD8tAJHzIb9-UydD4_a2SEbJh5XxPZXZ93kKNpiQ',
   'https://play-lh.googleusercontent.com/TtPDj4Y2E6_c8Iw3cA78IU-M2vIm2TzOyLzBXLi5zmOwhodLK3X-jFZhkq2olho0z6pB',
   'https://play-lh.googleusercontent.com/gVEW3TvGxz5Yh-XvQAenQFWeV8tRy9Hnczuof4l1NgoQpi74pmMTAgJC-_cH3jtK4_Iu',
   'https://play-lh.googleusercontent.com/p9tHQILmoUXq1rHO9In15Z3qgxo3icB5zM0Rj5xItIBJA694_H8CDwrfu5PjiiL4jq8',
   'https://play-lh.googleusercontent.com/-RgSS-aEepaJlnXJVf8BmCeuc62Omm5XDiyMT1io3G-d2zKLiSlMzxz634WKqSgbllc',
   'https://play-lh.googleusercontent.com/FOLYXDiNwSmpp3BHmLQETyqsSsjwti6lQeLnPvwx1xSGO8IlDQqGAwrGAn0WfX13Znc',
   'https://play-lh.googleusercontent.com/v44_fgsitw6b51KV3ULwT2BKV0ymuK_oUNxIOwJmkJcpPaEWgvYai-xzq--FTu5EMeXg',
   'https://play-lh.googleusercontent.com/2xjkkve0YDNsJSSJgydpE3uF9cKBAiXl5RGsrSa5GRP4L1bmr-FkKqPqU9MXmexjfgw',
   'https://play-lh.googleusercontent.com/P5nmJ0Ed8RWhN1akPjoLO619WV3RGdl5wagBbyrCfgfSYnCMmcSr_LddMNZVIpxe',
   'https://play-lh.googleusercontent.com/OBE1PTjsmE6wIn7QTg77ZNAnXTZUkvIHfqp4op0dSu3CbufkdOCJvsbQbrmTsjpaX4Y',
   'https://play-lh.googleusercontent.com/QOwKekrLJ5I4I2k7HweaRpgJ3cgtv606BRsa_aFv1ezvPWqWEofvy-IahVFeRDJnW7tW',
   'https://play-lh.googleusercontent.com/AAUL7K-E7TnRVFmFOOGi6D-Mb8akBs8d36fPs6lfTbtrheEirlFO68kULZaEvbQV2uU',
   'https://play-lh.googleusercontent.com/eQ3t1TksD87LD3cM5h1laWPTvj8O5WLSaezKaBqD5wSeNlbENGVl8IqkHoXJQncKHHk',
   'https://play-lh.googleusercontent.com/2juywVLj21-LisDhImwsDaUyqoJYzPkOh3gju-gEwdiIcwkEQC5WBdehp1_m0se3NA',
   'https://play-lh.googleusercontent.com/F2iHjopAqEtwtCe7YWILBzTGqZNgXQhOCDWscxDKjY-OndbwlCJVZ4dfGkxbvehIrIs',
   'https://play-lh.googleusercontent.com/zviFGW2hDHh5qrnBvDGx05dhryz62Vx7xY5rbUlSHbCHifHXnXrAHB93qecr42IIBfk',
   'https://play-lh.googleusercontent.com/HuReVcmZu16_IpUUkZ6rHnsr1rAwp-BzREl0U2DQy531EbrTkx64MtT8_pwmFrRQdMj6EdsiyYtmxrHbc1HA'],
  'title': 'Asphalt 8 - Car Racing Game',
  'score': 4.3038044,
  'genre': 'Racing',
  'price': 0,
  'free': True,
  'currency': 'INR',
  'video': 'https://www.youtube.com/embed/TEuZZB_zSOw?ps=play&vq=large&rel=0&autohide=1&showinfo=0',
  'videoImage': 'https://i.ytimg.com/vi/TEuZZB_zSOw/hqdefault.jpg',
  'description': "Part of Gameloft’s Asphalt franchise, Asphalt 8 is one of race car games offering an extensive collection of over 400+ licensed cars and motorbikes, delivering action-packed races across 75+ tracks. Immerse yourself in the thrilling world of high-speed racing as you jump into the driver's seat.\r\n\r\nExplore stunning scenarios and landscapes, ranging from the scorching Nevada Desert to the bustling streets of Tokyo. Compete against skilled racers, conquer exciting challenges, and engage in limited-time special racing events. Prepare your car for the ultimate test and unleash your drifting skills on the asphalt.\r\n\r\nLicensed luxury cars and motorcycles\r\nLuxury cars and motorcycles take center stage in Asphalt 8, with an impressive selection of top-tier vehicles from renowned manufacturers like Lamborghini, Bugatti, Porsche, and more. Experience the power of over 300 high-performance cars and motorcycles, alongside a wide variety of racing motorbikes. Customize and design your race cars and motorcycles to stand out from the crowd. Collect special-edition cars, explore diverse worlds and scenarios, all while perfecting your drifting technique.\r\n\r\nShow your racing style\r\nShowcase your unique racing style by unleashing your creativity and customizing your racer avatar. Mix and match clothes and accessories to craft a one-of-a-kind look that complements your car. Let your personality shine through as you dominate the racetrack.\r\n\r\nGet airborne with Asphalt 8\r\nPrepare for exhilarating gravity-defying action in Asphalt 8. Take your race to the skies as you hit ramps and perform breathtaking barrel rolls and 360° jumps. Compete against other racers or challenge yourself in single-player mode, executing daring mid-air maneuvers and stunts in your car or motorcycle to maximize your speed. Customize your controls and on-screen icons to suit your playstyle, ensuring victory in every race.\r\n\r\nEndless content for speed enthusiasts\r\nFuel your racing passion with a constant stream of fresh content. Experience regular updates, unlock powerful car upgrades, and dominate the competitive circuit. Explore seasons, engage in live events, and discover unique game modes. Compete in limited-time Cups to win valuable prizes, including early access to the latest cars and motorbikes.\r\n\r\nMultiplayer and single-player racing thrill\r\nImmerse yourself in thrilling multiplayer and single-player races. Join the multiplayer community, compete in the World Series, and challenge skilled opponents. Earn points, unlock prizes, and feel the adrenaline in limited-time racing events and racing passes. Fight for victory and savor the intensity of each race.\r\n\r\n_____________________________________________\r\nDon't forget to follow us on social media:\r\nDiscord: https://gmlft.co/A8-dscrd\r\nFacebook: https://gmlft.co/A8-Facebook\r\nTwitter: https://gmlft.co/A8-Twitter\r\nInstagram: https://gmlft.co/A8-Instagram\r\nYouTube: https://gmlft.co/A8-YouTube\r\n\r\nVisit our official site at http://gmlft.co/website_EN\r\nCheck out the new blog at http://gmlft.co/central\r\n\r\nThis app allows you to purchase virtual items within the app and may contain third-party advertisements that may redirect you to a third-party site.\r\n\r\nPrivacy Policy: http://www.gameloft.com/en/privacy-notice\r\nTerms of Use: http://www.gameloft.com/en/conditions-of-use\r\nEnd-User License Agreement: http://www.gameloft.com/en/eula",
  'descriptionHTML': 'Part of Gameloft’s Asphalt franchise, Asphalt 8 is one of race car games offering an extensive collection of over 400+ licensed cars and motorbikes, delivering action-packed races across 75+ tracks. Immerse yourself in the thrilling world of high-speed racing as you jump into the driver&#39;s seat.<br><br>Explore stunning scenarios and landscapes, ranging from the scorching Nevada Desert to the bustling streets of Tokyo. Compete against skilled racers, conquer exciting challenges, and engage in limited-time special racing events. Prepare your car for the ultimate test and unleash your drifting skills on the asphalt.<br><br>Licensed luxury cars and motorcycles<br>Luxury cars and motorcycles take center stage in Asphalt 8, with an impressive selection of top-tier vehicles from renowned manufacturers like Lamborghini, Bugatti, Porsche, and more. Experience the power of over 300 high-performance cars and motorcycles, alongside a wide variety of racing motorbikes. Customize and design your race cars and motorcycles to stand out from the crowd. Collect special-edition cars, explore diverse worlds and scenarios, all while perfecting your drifting technique.<br><br>Show your racing style<br>Showcase your unique racing style by unleashing your creativity and customizing your racer avatar. Mix and match clothes and accessories to craft a one-of-a-kind look that complements your car. Let your personality shine through as you dominate the racetrack.<br><br>Get airborne with Asphalt 8<br>Prepare for exhilarating gravity-defying action in Asphalt 8. Take your race to the skies as you hit ramps and perform breathtaking barrel rolls and 360° jumps. Compete against other racers or challenge yourself in single-player mode, executing daring mid-air maneuvers and stunts in your car or motorcycle to maximize your speed. Customize your controls and on-screen icons to suit your playstyle, ensuring victory in every race.<br><br>Endless content for speed enthusiasts<br>Fuel your racing passion with a constant stream of fresh content. Experience regular updates, unlock powerful car upgrades, and dominate the competitive circuit. Explore seasons, engage in live events, and discover unique game modes. Compete in limited-time Cups to win valuable prizes, including early access to the latest cars and motorbikes.<br><br>Multiplayer and single-player racing thrill<br>Immerse yourself in thrilling multiplayer and single-player races. Join the multiplayer community, compete in the World Series, and challenge skilled opponents. Earn points, unlock prizes, and feel the adrenaline in limited-time racing events and racing passes. Fight for victory and savor the intensity of each race.<br><br>_____________________________________________<br>Don&#39;t forget to follow us on social media:<br>Discord: https://gmlft.co/A8-dscrd<br>Facebook: https://gmlft.co/A8-Facebook<br>Twitter: https://gmlft.co/A8-Twitter<br>Instagram: https://gmlft.co/A8-Instagram<br>YouTube: https://gmlft.co/A8-YouTube<br><br>Visit our official site at http://gmlft.co/website_EN<br>Check out the new blog at http://gmlft.co/central<br><br>This app allows you to purchase virtual items within the app and may contain third-party advertisements that may redirect you to a third-party site.<br><br>Privacy Policy: http://www.gameloft.com/en/privacy-notice<br>Terms of Use: http://www.gameloft.com/en/conditions-of-use<br>End-User License Agreement: http://www.gameloft.com/en/eula',
  'developer': 'Gameloft SE',
  'installs': '500,000,000+'},
 {'appId': 'com.ea.game.nfs14_row',
  'icon': 'https://play-lh.googleusercontent.com/ucM_ts5bbrPW6RoICKkB9ci89-U047JlW3Wopq2hOxkrHNgzONz3M3fiUbJA_YjmbrxE',
  'screenshots': ['https://play-lh.googleusercontent.com/HehGoNlbNKBOJinpqTAYPJCiL6xN1K2IOWlgD78ndgd9aQxZAmXsGEobCF-6s33n8w',
   'https://play-lh.googleusercontent.com/2mAzposcnKAMwjBce47ZC3_LLlHn6oqHvuX8cp1r4TeJzXzbVQOG4Fe977T5QX0xjRE',
   'https://play-lh.googleusercontent.com/Q61zSzTJSybptSvSLQkHcc3EJLL2wniGBuwHeZ12O-ZeBxhgOGrBtqsPmPIuvEAIaA',
   'https://play-lh.googleusercontent.com/Ip7c5H0-lNsphhv_VbiyXtii0Pcr3Wakw7iUGUO63eGE8hwfiQcj61PdTDEUg-0WY_M',
   'https://play-lh.googleusercontent.com/-0ZR9uagLkLrnoCJsb3kCnapkGo2X0Jaz8m2W9Kr6M9KTBqU2p7UPin72BO8rXU4pA',
   'https://play-lh.googleusercontent.com/vk42x_SnhB_ZsLi9htXRxXQJmUGJ_k09K-lIgD1l-6xOZu_jtMD1JmhrNZWBv26gIgI',
   'https://play-lh.googleusercontent.com/t-44PqS0b2o7CzMDE2tbQAlPiUmSIWmLHBXc_osrQMKFoo_lj4U57LOqd-5AzeX2LQ',
   'https://play-lh.googleusercontent.com/pNZsNzt3ZdExhaOkpUTbLWtfj4kL9cpQXcjX6CsIJXM9xnPiVSQi_2FpOvv4TGRkphjV',
   'https://play-lh.googleusercontent.com/Qu3gwtye5InKKVUps_9utyL5Dz6eZ7ekGpg2Xi1HLpenjN75bZf5oHQfhHTonUWnRVj1',
   'https://play-lh.googleusercontent.com/J2RfrbtP7n-_sbGzqIJZBEpnZVBzoX_XqTjKOcyLgRcr1luiludkssonS-6ib_p7ow',
   'https://play-lh.googleusercontent.com/9vYVDu9olmX6neWoB7N1k4bi7yBwZx0tp_ZsYkwvT69QdjAC0m8ovIOU7DZA2-hAzBlh',
   'https://play-lh.googleusercontent.com/kDIEyUdCz8xVUvWYMMe3Xrf5etfibccIC8kgP8njMBRYUXDQutHKVXL0yoMsPcXbcdU',
   'https://play-lh.googleusercontent.com/0FLoI6E1DP_js14tsbzs4rDEpzzPUGCvcgwiVcRiwhOLrZKXfBI3jbCSEzQFnBNA',
   'https://play-lh.googleusercontent.com/RVoGhR1f9Pmo4hftoCEVTeG1cJ369y0ZfPAy4SqguKJvmHtW0jqfIsdtxtr74t-MS2jl',
   'https://play-lh.googleusercontent.com/mlhQI-sM9HAE_XwiFfR3im7q3ndMZ14irAxIRVuf8WSOZu-vvrJJbVA8XR4BsLOND4Om',
   'https://play-lh.googleusercontent.com/vFHBc4fAzrnBncPZO6Nkj0aN7YqVhapQxjj3pXmVrg0wObjW4kFArqtYbVdZM0lIDGKd',
   'https://play-lh.googleusercontent.com/TlL0PHOo-PovT2C7q_J-ZcXApf4r47G2q-Tt54PppykRR4ay51ZDm5Zz6gedKKuTFgk',
   'https://play-lh.googleusercontent.com/gVxSxBQ0rBKYhvhvLU46booxSS3ijRgq2_ShzD0_LwF2lzO0qUDi0I6bgwHJviQHCpSw',
   'https://play-lh.googleusercontent.com/qliu2arQsd0RrZZ_EYNGUzWlk8vDkpup1MTYnrcl69bv6fIEJEkOqAAfwf7jiIa9BMY'],
  'title': 'Need for Speed™ No Limits',
  'score': 4.0658584,
  'genre': 'Racing',
  'price': 0,
  'free': True,
  'currency': 'INR',
  'video': 'https://www.youtube.com/embed/ueKe5DXOcBM?ps=play&vq=large&rel=0&autohide=1&showinfo=0',
  'videoImage': 'https://i.ytimg.com/vi/ueKe5DXOcBM/hqdefault.jpg',
  'description': 'Rule the street racing Underground as you race in the first Need for Speed made just for mobile! Conquer the asphalt of Blackridge city, engage your nitro, and tune your cars — from the game developer that brought you Real Racing 3! \r\n\r\nBuild the car collection of your dreams by acquiring cars, tuning them, and customizing them to your style. Launch yourself between chaos and control as you drift and roll into underground street racing. \r\n\r\nTake down the competition, engage your nitro, up your street rep, and burst into traffic - more races, customizations, and cars! Leave your mark on the city and never look back in this exciting racing game.\r\n\r\nNote: This app offers in-app purchases. You may disable in-app purchases using your device settings.\r\n\r\nA RACING GAME WITH NO LIMITS\r\n\r\nBecome a master car builder with the customization system, giving you over 2.5 million tuning combos to play with. Your rides are waiting – test them on the asphalt of the city’s street racing scene.\r\n\r\nLevel-up your driving game with the real-world dream cars you’ve always wanted - from manufacturers such as Bugatti, Lamborghini, McLaren, and many more top car brands. \r\n\r\nDRIVE FAST — AND FEARLESS\r\n\r\nSteer onto the asphalt of the Blackridge street racing scene, zip around debris, into traffic, against walls, and through high-speed Nitro Zones!\r\n\r\nAround every corner is a fresh racing rival — clash with local crews and evade cops. Get your driving game face on and earn unparalleled respect.\r\n\r\nRACE TO WIN\r\n\r\nNever back down as you take on extreme street racing, and never stop hitting nitro against anyone crazy enough to take you on. Increase your rep by any means necessary!\r\n\r\nDrift, drag, and roll your ride to the finish line while outrunning the police on your tail. Heat up the asphalt in over 1,000 challenging races in the infamous street racing city. Invest further into car tuning, be notorious, don’t save your nitro — and change the racing game forever!\r\n\r\n---------------------\r\nUser Agreement: terms.ea.com\r\nVisit https://help.ea.com/ for assistance or inquiries.\r\n\r\nEA may retire online features and services after 30 days’ notice posted on www.ea.com/1/service-updates\r\n\r\nImportant Consumer Information:\r\n\r\nThis app: requires a persistent Internet connection (network fees may apply); Requires acceptance of EA’s Privacy & Cookie Policy and User Agreement. includes in-game advertising; collects data through third party analytics technology (see Privacy & Cookie Policy for details); contains direct links to the Internet and social networking sites intended for an audience over 13.',
  'descriptionHTML': 'Rule the street racing Underground as you race in the first Need for Speed made just for mobile! Conquer the asphalt of Blackridge city, engage your nitro, and tune your cars — from the game developer that brought you Real Racing 3! <br><br>Build the car collection of your dreams by acquiring cars, tuning them, and customizing them to your style. Launch yourself between chaos and control as you drift and roll into underground street racing. <br><br>Take down the competition, engage your nitro, up your street rep, and burst into traffic - more races, customizations, and cars! Leave your mark on the city and never look back in this exciting racing game.<br><br>Note: This app offers in-app purchases. You may disable in-app purchases using your device settings.<br><br>A RACING GAME WITH NO LIMITS<br><br>Become a master car builder with the customization system, giving you over 2.5 million tuning combos to play with. Your rides are waiting – test them on the asphalt of the city’s street racing scene.<br><br>Level-up your driving game with the real-world dream cars you’ve always wanted - from manufacturers such as Bugatti, Lamborghini, McLaren, and many more top car brands. <br><br>DRIVE FAST — AND FEARLESS<br><br>Steer onto the asphalt of the Blackridge street racing scene, zip around debris, into traffic, against walls, and through high-speed Nitro Zones!<br><br>Around every corner is a fresh racing rival — clash with local crews and evade cops. Get your driving game face on and earn unparalleled respect.<br><br>RACE TO WIN<br><br>Never back down as you take on extreme street racing, and never stop hitting nitro against anyone crazy enough to take you on. Increase your rep by any means necessary!<br><br>Drift, drag, and roll your ride to the finish line while outrunning the police on your tail. Heat up the asphalt in over 1,000 challenging races in the infamous street racing city. Invest further into car tuning, be notorious, don’t save your nitro — and change the racing game forever!<br><br>---------------------<br>User Agreement: terms.ea.com<br>Visit https://help.ea.com/ for assistance or inquiries.<br><br>EA may retire online features and services after 30 days’ notice posted on www.ea.com/1/service-updates<br><br>Important Consumer Information:<br><br>This app: requires a persistent Internet connection (network fees may apply); Requires acceptance of EA’s Privacy &amp; Cookie Policy and User Agreement. includes in-game advertising; collects data through third party analytics technology (see Privacy &amp; Cookie Policy for details); contains direct links to the Internet and social networking sites intended for an audience over 13.',
  'developer': 'ELECTRONIC ARTS',
  'installs': '100,000,000+'},
 {'appId': 'com.naturalmotion.customstreetracer2',
  'icon': 'https://play-lh.googleusercontent.com/m--ur2Kv3Ccw-9dEPp9DTN7CVBfbgWqX8rCiNiVK8IHPU1M9OcgJYe5M-0aM1y2n5w',
  'screenshots': ['https://play-lh.googleusercontent.com/1lxjoEwKbEE_N7Mx8HavjwF7uw45XMbyTUtm6QGt-gJtKlcoN37q5BHdZescFgaB1EE',
   'https://play-lh.googleusercontent.com/yWLopzJ61RLfkBQ-yL3JgNXEnTSF0xYkwvjUi-wTCldaSNjMBn0XCAtXbYWI5WYCd8Uy',
   'https://play-lh.googleusercontent.com/3BRSTt8LQ9KGI3Mix21BlXyalGRsnGGy30oAmU7K6W1YH-Jn6HmOpq_wUA5R43cnB-0',
   'https://play-lh.googleusercontent.com/EY-0jgVdnN83nNMb5DsBD7PyM26Gm4XauclCVMBc7Z5ExTNikLHBobo1ptHpJBlHqA',
   'https://play-lh.googleusercontent.com/OrmrrK4bm7VrfAsNhNmixaYP_tvT_x5W83DviTuQSgzebEOWGu7H9HEEK8iGmW-86hHD',

In [15]:
type(games)

list

In [16]:
len(games)

10

In [17]:
games[0].keys()

dict_keys(['appId', 'icon', 'screenshots', 'title', 'score', 'genre', 'price', 'free', 'currency', 'video', 'videoImage', 'description', 'descriptionHTML', 'developer', 'installs'])

In [18]:
games[0]["appId"]

'com.gameloft.android.ANMP.GloftA8HM'

In [19]:
i = 0
while i < len(games):
    print(games[i]["appId"])
    i += 1

com.gameloft.android.ANMP.GloftA8HM
com.ea.game.nfs14_row
com.naturalmotion.customstreetracer2
com.gameloft.android.ANMP.GloftA9HM
com.carxtech.sr
game.revani.racemaxpro
com.easygames.race
com.ea.games.r3_row
com.olzhas.carparking.multyplayer
com.carxtech.carxdr2

In [20]:
for i in range(len(games)):
    print(games[i]["appId"])

com.gameloft.android.ANMP.GloftA8HM
com.ea.game.nfs14_row
com.naturalmotion.customstreetracer2
com.gameloft.android.ANMP.GloftA9HM
com.carxtech.sr
game.revani.racemaxpro
com.easygames.race
com.ea.games.r3_row
com.olzhas.carparking.multyplayer
com.carxtech.carxdr2

In [26]:
md = search("Top social media app", n_hits = 10, lang = "en", country = "in")

In [27]:
md

[{'appId': 'com.twitter.android',
  'icon': 'https://play-lh.googleusercontent.com/A-Rnrh0J7iKmABskTonqFAANRLGTGUg_nuE4PEMYwJavL3nPt5uWsU2WO_DSgV_mOOM',
  'screenshots': ['https://play-lh.googleusercontent.com/V0Fui04S8jpx5Ib0tByOpsaUhTq3VxR8POtSvzycQxH3aj3-LJZA2XXSW5iyDF8aJMzikfuET2cbC0WE8IHe',
   'https://play-lh.googleusercontent.com/9VlDdg-PYd7PJkxe324CwF6l3aXS9VCjIr-NcX8n4oabLCxTssCdnCELZVxqBDt6fhGWi8-wE751Iy6Pova8',
   'https://play-lh.googleusercontent.com/iW-TrXQ_w_Ncq9J73mhhY6DF9gsEKIAz5amwjx0WI_l_1tuzayLzLPC4TyS0u_I7MjBq62KjIcsJCIzdwll4',
   'https://play-lh.googleusercontent.com/LbI1Su3cp-mzo0xGE2A_Bnz9iE7nisayuWKHcDwzqeiksnHi_BFFmXq_co0n8lbPdLx-tfFe3PX6Ym1IfnP1',
   'https://play-lh.googleusercontent.com/SvxdK_-u0QXglCl1KmEXH5arSM5bAdwJuo51wGfaLm2oP5vYqKImMutOkSSdnBysfqTk4zvr929Ku7a0Uuj2fA',
   'https://play-lh.googleusercontent.com/aw6ogd0QJOeNGE6OMuJyvuo4Li7Zd1y07nVWRUjx7Y0LrifavQ8u0H51niTb3VEKYEWruh3MaV-LlqARZzxPbA',
   'https://play-lh.googleusercontent.com/rIYDY0eqsU-0YnEOYfjnvVC_e27KxQkAG2yaNPXi6jrsPTNeGMILZi1fqPSRdBUo4NKkxmlHeQQcEE0t9i9D',
   'https://play-lh.googleusercontent.com/fnPna8zF5PnMjHqOTlBZnmiD8vJ-yHYb58vecsZ2H7GjcLzuUAkvCymthrHLi0pi7kpn'],
  'title': 'X (Formerly Twitter)',
  'score': 4.003483,
  'genre': 'News & Magazines',
  'price': 0,
  'free': True,
  'currency': 'INR',
  'video': None,
  'videoImage': None,
  'description': "X – The Everything App for Breaking News, Live Conversations, and Social Streaming\r\n\r\nWelcome to X, your trusted digital town square, where conversations unfold in real time, and the world connects through breaking news, live events, podcasts, and everything in between. Whether you're passionate about sports, tech, music, or politics, X is your front-row seat to what’s happening across the globe.\r\n\r\nX isn’t just another social media app, it’s the ultimate destination for staying well informed, sharing ideas, and building communities. With X, you’re always in the loop with relevant trending topics and breaking news, delivered instantly to your screen, raw and unfiltered.\r\n\r\nWhat You Can Do on X:\r\n• Follow breaking news from around the world before it hits the headlines, and stay ahead of the curve with real-time updates on trending topics and viral conversations.\r\n\r\n• Post your thoughts, photos, and videos with a global community. Join millions of users in shaping public dialogue across social, cultural, and political conversations.\r\n\r\n• Discover Grok, the AI assistant powered by X’s real-time data. You can ask Grok to summarize trending news, explain videos, or give you more context about posts.\r\n\r\n• Stream live video or go live with Spaces, our audio feature that enables you to host discussions, hold interviews, or start your next live podcast. Whether you're streaming a concert, a live game, or your thoughts on a hot topic, X keeps your audience engaged.\r\n\r\n• Watch videos: from live breaking news and sports clips to podcasts and gaming sessions that last up to 3 hours long. Many of the world’s leading voices, in comedy, gaming, podcasting, and politics, all share their content on X.\r\n\r\n• Connect and chat privately with friends, followers, customers, or collaborators through Direct Messages.\r\n\r\n• Join and build communities tailored to your interests: from sports news, gaming, entertainment, crypto, entrepreneurship, tech, and more.\r\n\r\n• Subscribe to X Premium to unlock exclusive features like a blue checkmark, boosted visibility, prioritized replies, fewer ads, longer videos, and post editing. X Premium also gives you access to creator revenue sharing and the ability to offer exclusive content to subscribers.\r\n\r\nWhy X?\r\nIn a world of constant change, X is your real-time source to stay ahead of the curve, connect with people, and explore diverse perspectives. From breaking live news and trending memes to top podcasts and live streams from your favorite creators, X brings it all together in one powerful social experience.",
  'descriptionHTML': 'X – The Everything App for Breaking News, Live Conversations, and Social Streaming<br><br>Welcome to X, your trusted digital town square, where conversations unfold in real time, and the world connects through breaking news, live events, podcasts, and everything in between. Whether you&#39;re passionate about sports, tech, music, or politics, X is your front-row seat to what’s happening across the globe.<br><br>X isn’t just another social media app, it’s the ultimate destination for staying well informed, sharing ideas, and building communities. With X, you’re always in the loop with relevant trending topics and breaking news, delivered instantly to your screen, raw and unfiltered.<br><br>What You Can Do on X:<br>• Follow breaking news from around the world before it hits the headlines, and stay ahead of the curve with real-time updates on trending topics and viral conversations.<br><br>• Post your thoughts, photos, and videos with a global community. Join millions of users in shaping public dialogue across social, cultural, and political conversations.<br><br>• Discover Grok, the AI assistant powered by X’s real-time data. You can ask Grok to summarize trending news, explain videos, or give you more context about posts.<br><br>• Stream live video or go live with Spaces, our audio feature that enables you to host discussions, hold interviews, or start your next live podcast. Whether you&#39;re streaming a concert, a live game, or your thoughts on a hot topic, X keeps your audience engaged.<br><br>• Watch videos: from live breaking news and sports clips to podcasts and gaming sessions that last up to 3 hours long. Many of the world’s leading voices, in comedy, gaming, podcasting, and politics, all share their content on X.<br><br>• Connect and chat privately with friends, followers, customers, or collaborators through Direct Messages.<br><br>• Join and build communities tailored to your interests: from sports news, gaming, entertainment, crypto, entrepreneurship, tech, and more.<br><br>• Subscribe to X Premium to unlock exclusive features like a blue checkmark, boosted visibility, prioritized replies, fewer ads, longer videos, and post editing. X Premium also gives you access to creator revenue sharing and the ability to offer exclusive content to subscribers.<br><br>Why X?<br>In a world of constant change, X is your real-time source to stay ahead of the curve, connect with people, and explore diverse perspectives. From breaking live news and trending memes to top podcasts and live streams from your favorite creators, X brings it all together in one powerful social experience.',
  'developer': 'X Corp.',
  'installs': '1,000,000,000+'},
 {'appId': 'com.instagram.android',
  'icon': 'https://play-lh.googleusercontent.com/VRMWkE5p3CkWhJs6nv-9ZsLAs1QOg5ob1_3qg-rckwYW7yp1fMrYZqnEFpk0IoVP4LM',
  'screenshots': ['https://play-lh.googleusercontent.com/n74uQe2LDP6pqPQvDsgN8pabNNc8NdShoRzbA7gr7Hd9Y9clPkZ5Xg2L1osnPqTJC9IHHYD867RC3eDORxDd',
   'https://play-lh.googleusercontent.com/_K0t5bG4GM30T6QF6onfa4Xbp1fjgXuB1EQBTaCY_CS2_agQKvxB2SBQxEPjnP6-AY9bNrHAjxSGXCwFNO9RMQ',
   'https://play-lh.googleusercontent.com/Ovro78HjEglmrw0VggPyZnjoVSaH_odOdTnDh52LyCH6OtB3gQyq9qT86N0p7CuWg22YVjP-siq0x5PlqxVQWX0',
   'https://play-lh.googleusercontent.com/6gTZ3MuWAe10qEjX4JmFVZdyAqxYcigwvgixrx8eI8Llbmkd9UzJtkIsLSKkLBM5QFLNp6a4eXknqMTt0uks7A',
   'https://play-lh.googleusercontent.com/KBU8I0Z76oAnpQ9K2zNGs6-mi3O3O_m9c_V-BlRF90lh2jjll4uE8nQ4-zIXgM4rPbmr4pPfImEIC6Ze_CNT_Go',
   'https://play-lh.googleusercontent.com/AGsm7HoW9NbRwzSGHqCGVx-Hz9v2ps2nBAz0uKnxg95xfuO82ESNCN50y1-M2oxhR09Zq74naiWa3ECd809qNg',
   'https://play-lh.googleusercontent.com/1jevwdYf5vTIoTInKEV3XF0bQw_tqF4-umAV5CYO-CZ9CPN0tc5CAdUkMt-yCPPtqFKZK12AyrbR3SsXrJT9kZM',
   'https://play-lh.googleusercontent.com/CgUPurtUp8SB709wsQcKLMv6JdIh1em0ka_58V69AorznLv42TV39etS2rt28wv9Rz8'],
  'title': 'Instagram',
  'score': 4.3101363,
  'genre': 'Social',
  'price': 0,
  'free': True,
  'currency': 'INR',
  'video': 'https://www.youtube.com/embed/7wbnqYRz6jE?ps=play&vq=large&rel=0&autohide=1&showinfo=0',
  'videoImage': 'https://i.ytimg.com/vi/7wbnqYRz6jE/hqdefault.jpg',
  'description': "Little moments lead to big friendships. Share yours on Instagram. \r\n—From Meta\r\n\r\nConnect with friends, find other fans, and see what people around you are up to and into. Explore your interests and post what's going on, from your daily moments to life's highlights.\r\n\r\nShare what you’re up to and into on Insta®.\r\n- Keep up with friends on the fly with Stories and Notes that disappear after 24 hours.\r\n- Start group chats and share unfiltered moments with your Close Friends.\r\n- Share memories from recent events or trips in Feed.\r\n- Turn your life into a movie and discover short, entertaining videos on Instagram with Reels.\r\n- Customize your posts with exclusive templates, music, stickers and filters.\r\n\r\nDive into your interests.\r\n- Watch videos from your favorite Creators and discover new content that’s personalized to your interests.\r\n- Get inspired by photos and videos from new accounts in Explore.\r\n- Discover brands and small businesses, and shop products that are relevant to your personal style.\r\n\r\nSome Instagram features may not be available in your country or region.\r\n\r\nTerms and Policies - https://help.instagram.com/581066165581870\r\n\r\nConsumer Health Privacy Policy: https://privacycenter.instagram.com/policies/health\r\n\r\nLearn how we're working to help keep our communities safe across Meta technologies at the Instagram Safety Center: https://about.instagram.com/safety",
  'descriptionHTML': 'Little moments lead to big friendships. Share yours on Instagram. <br>—From Meta<br><br>Connect with friends, find other fans, and see what people around you are up to and into. Explore your interests and post what&#39;s going on, from your daily moments to life&#39;s highlights.<br><br>Share what you’re up to and into on Insta®.<br>- Keep up with friends on the fly with Stories and Notes that disappear after 24 hours.<br>- Start group chats and share unfiltered moments with your Close Friends.<br>- Share memories from recent events or trips in Feed.<br>- Turn your life into a movie and discover short, entertaining videos on Instagram with Reels.<br>- Customize your posts with exclusive templates, music, stickers and filters.<br><br>Dive into your interests.<br>- Watch videos from your favorite Creators and discover new content that’s personalized to your interests.<br>- Get inspired by photos and videos from new accounts in Explore.<br>- Discover brands and small businesses, and shop products that are relevant to your personal style.<br><br>Some Instagram features may not be available in your country or region.<br><br>Terms and Policies - https://help.instagram.com/581066165581870<br><br>Consumer Health Privacy Policy: https://privacycenter.instagram.com/policies/health<br><br>Learn how we&#39;re working to help keep our communities safe across Meta technologies at the Instagram Safety Center: https://about.instagram.com/safety',
  'developer': 'Instagram',
  'installs': '5,000,000,000+'},
 {'appId': 'com.truthsocial.android.app',
  'icon': 'https://play-lh.googleusercontent.com/viE7sFTiSuKKSnbzWHPcMpIKlKbZgWMw11bTeM2pUCV4o4lbFrzXJF8WHt88kni1q1YX',
  'screenshots': ['https://play-lh.googleusercontent.com/BofhXneR-AQqAocvXiLnO9Mr6MZUnAHNUko2A4mx09UtAFeYsLDILm8IJPLxN2Z1EDA',
   'https://play-lh.googleusercontent.com/6RtojegGM6JHAgvEMbCoMLuKu2vcbQOcMP6m8LHZlFN4YRPmrPYyYGt7nvRlXDoV-A',
   'https://play-lh.googleusercontent.com/_PSZo0beSAgTc9CM944cblfoU1CnI-L6Y3dit6_JvzvsmJvUUO-EPgNU3R_fF9jpx6nY',
   'https://play-lh.googleusercontent.com/PVBJnDcQV4wtT02bn4_wFqFwVvtNMyQGtSlG_FGU2RRD1vyn6OC2jdNwaWCRWv-a3SA',
   'https://play-lh.googleusercontent.com/TM3s0ppvqnyFycZ2bN56ODEpwcUfvaP4a5HdLOGhhmLiO0zy_eHDengzUHjkDEtAbQw',
   'https://play-lh.googleusercontent.com/Rf0hsTGnRKGiJSE9noTiBYtpqT4Hpwp3cpFxTqX75jsyzhPi3feWw36Q8xGbSabLEyg',
   'https://play-lh.googleusercontent.com/wyI7xreFOytJ7JLIH5jnWFEsAX95WcKw6klMPv1ZVmAtsapndjCOqM5YuFUOXyxRqFOa',
   'https://play-lh.googleusercontent.com/fk6VgihNG0MxECoenOsKTn1XMmFrrb5Dz0u8dA6wQZjX_jV0tpUGbHidWB_M4TLmxxI',
   'https://play-lh.googleusercontent.com/8dIjH7hqDAitjumCLds_Zo9SJlH8G9K1bfELLA-UNq6d_RxzH8urp-FErfmpBwSxRM4'],
  'title': 'Truth Social',
  'score': 1.21,
  'genre': 'Social',
  'price': 0,
  'free': True,
  'currency': 'INR',
  'video': None,
  'videoImage': None,
  'description': "The #1 free-speech social media platform is now available as a native Android app!\r\n\r\nIn the year 2021, the media pendulum has swung dangerously far to the left. Silicon Valley, the mainstream media, and Big Tech have begun to forcibly silence voices that do not align with their woke ideology. Big Tech platforms demonetize, throttle, and cancel those who stray from the mainstream narrative. They are not just censoring content – they are determining what can and cannot be said. By controlling how information is shared, they control the narrative. They control the future. They control you.\r\n\r\nTo counter this dangerous exercise of Big Tech monopoly power, Truth Social intends to even the playing field by providing people with an open media platform where they can share and create content without fear of reputational ruin.\r\n\r\nNo political discrimination.\r\nCanceling cancel culture.\r\nStanding up to Big Tech.\r\n\r\nJoin us.\r\n\r\nKey Features\r\n\r\nProfile - Express your unique personality by setting up a profile, avatar, and background. Begin to track your personal connections through follower and following counts as well as history for your posts and likes.\r\n\r\nTruth Feed - Get the scoop on the latest thoughts and activities from the people, organizations, and news outlets that interest you. The Truth Feed contains posts from all those you follow brought to life with the help of thumbnail photos, links, and more.\r\n\r\nCompose Truths - Let your voice be heard. Sign up, join the conversation, and share your unique opinion by posting a Truth, Re-Truth, photo, news story, poll or video link to communicate with your friends, customers, and the world. Stay informed about breaking news while staying directly connected with the people who influence you – don't be shocked if they take your Truth viral!\r\n\r\nSearch - Truth Social really starts to become interesting as you connect with others. Search for a voice that you find interesting and easily follow them right from the search list or view their profile first before deciding.\r\n\r\nDirect Messages - Take your conversations private by direct messaging your followers for 1-on-1 chats! Set messages to auto-delete after 7, 14, 30, or 90 days on a per-chat basis. Silence push notifications for all chats or on a per-chat basis. You can also turn off the ability for those you follow to DM you (in your Preferences) as well as block users, copy, delete and report messages.\r\n\r\nPolls – Create polls to get feedback on a question you may have.\r\n\r\nNotifications - Stay engaged as you build a following. See who's following you and who's interacting with your Truths.",
  'descriptionHTML': 'The #1 free-speech social media platform is now available as a native Android app!<br><br>In the year 2021, the media pendulum has swung dangerously far to the left. Silicon Valley, the mainstream media, and Big Tech have begun to forcibly silence voices that do not align with their woke ideology. Big Tech platforms demonetize, throttle, and cancel those who stray from the mainstream narrative. They are not just censoring content – they are determining what can and cannot be said. By controlling how information is shared, they control the narrative. They control the future. They control you.<br><br>To counter this dangerous exercise of Big Tech monopoly power, Truth Social intends to even the playing field by providing people with an open media platform where they can share and create content without fear of reputational ruin.<br><br>No political discrimination.<br>Canceling cancel culture.<br>Standing up to Big Tech.<br><br>Join us.<br><br>Key Features<br><br>Profile - Express your unique personality by setting up a profile, avatar, and background. Begin to track your personal connections through follower and following counts as well as history for your posts and likes.<br><br>Truth Feed - Get the scoop on the latest thoughts and activities from the people, organizations, and news outlets that interest you. The Truth Feed contains posts from all those you follow brought to life with the help of thumbnail photos, links, and more.<br><br>Compose Truths - Let your voice be heard. Sign up, join the conversation, and share your unique opinion by posting a Truth, Re-Truth, photo, news story, poll or video link to communicate with your friends, customers, and the world. Stay informed about breaking news while staying directly connected with the people who influence you – don&#39;t be shocked if they take your Truth viral!<br><br>Search - Truth Social really starts to become interesting as you connect with others. Search for a voice that you find interesting and easily follow them right from the search list or view their profile first before deciding.<br><br>Direct Messages - Take your conversations private by direct messaging your followers for 1-on-1 chats! Set messages to auto-delete after 7, 14, 30, or 90 days on a per-chat basis. Silence push notifications for all chats or on a per-chat basis. You can also turn off the ability for those you follow to DM you (in your Preferences) as well as block users, copy, delete and report messages.<br><br>Polls – Create polls to get feedback on a question you may have.<br><br>Notifications - Stay engaged as you build a following. See who&#39;s following you and who&#39;s interacting with your Truths.',
  'developer': 'T Media Tech LLC',
  'installs': '5,000,000+'},
 {'appId': 'com.facebook.katana',
  'icon': 'https://play-lh.googleusercontent.com/KCMTYuiTrKom4Vyf0G4foetVOwhKWzNbHWumV73IXexAIy5TTgZipL52WTt8ICL-oIo',
  'screenshots': ['https://play-lh.googleusercontent.com/PQ-I5iK74sGn8nu6dGAY37ThWXeRElBnjMI7yltIX_NWrvBBiPMTH_c5TNana2U95aY',
   'https://play-lh.googleusercontent.com/xZvLOXywytpEWzCe-2DjND0ULv5MdbK5GXOC1brO805gkaIwgj7Rwk7eqnxWfzDIy0g',
   'https://play-lh.googleusercontent.com/pn8T4CKPboul4qoMDoyEifxA29B5wZnH9LeIq_c7kCxn64igss56SilQ-mNl8EkmrkKB',
   'https://play-lh.googleusercontent.com/3GB2SzWY1-qZArFJ5CsWeyeb0ccPQplbKmSA44scVTtLXTfVmaxOVGzMsU2OLlBUlnA',
   'https://play-lh.googleusercontent.com/iC8pEw77IjhHxqTWHLjh7P-pzTAfVBnxl1U9ctY9dX9euHCAsYh8lZ1kxL16O6OmFBc',
   'https://play-lh.googleusercontent.com/vqK8B3MyzTX04co89ft28ntB6UxqpFdpuFlqBW8n8c3lvEIOizxtIGUDYP1dqjW7qA',
   'https://play-lh.googleusercontent.com/xMFFClUDUfjuc2WJfYANsTzHwCNw_VRyek7g5ryiJssJu4W3TKfwr-oSfs5IUnukYiU43sWlXK881iEvi4weJLI',
   'https://play-lh.googleusercontent.com/m-6SmkHqMLQrJOV-2B78gYMhNo2M0w1uJSdJgXPldJzbYetRuwjhN5_nUVpve6aQ_nFTO7v2e4tW5Uckh0YA',
   'https://play-lh.googleusercontent.com/GQXolHad8JJu_qR90bF9krWLP66RimpNgskSMXEcmoZ1znWfgsB8uCtM1uGC0n_lMA'],
  'title': 'Facebook',
  'score': 4.3487024,
  'genre': 'Social',
  'price': 0,
  'free': True,
  'currency': 'INR',
  'video': None,
  'videoImage': None,

In [23]:
len(md)

10

In [24]:
md[0].keys()

dict_keys(['appId', 'icon', 'screenshots', 'title', 'score', 'genre', 'price', 'free', 'currency', 'video', 'videoImage', 'description', 'descriptionHTML', 'developer', 'installs'])

In [29]:
i = 0
while i < len(md):
    print(md[i]["appId"])
    i += 1

com.twitter.android
com.instagram.android
com.truthsocial.android.app
com.facebook.katana
com.instagram.barcelona
com.tumblr
com.reddit.frontpage
com.fanbase
com.clubhouse.app
xyz.blueskyweb.app

In [30]:
for i in range(len(md)):
    print(md[i]["installs"])

1,000,000,000+
5,000,000,000+
5,000,000+
10,000,000,000+
100,000,000+
100,000,000+
100,000,000+
500,000+
10,000,000+
10,000,000+

In [4]:
appids = []
query = int(input("Enter How many no. of query you want"))
i = 1
while i <= query:
    result = search(query = input(f"Query no. {i}.."), n_hits = 10, country = "in")
    j = 0
    while j < len(result):
        appid = result[j]["appId"]
        appids.append(appid)
        j += 1
    i += 1

Enter How many no. of query you want 5
Query no. 1.. Top car's games
Query no. 2.. Top Video Editing app
Query no. 3.. Top Kids games
Query no. 4.. Top cricket games
Query no. 5.. Top Bike games

In [5]:
appids

['com.gameloft.android.ANMP.GloftA8HM',
 'com.aim.racing',
 'com.naturalmotion.customstreetracer2',
 'com.ea.game.nfs14_row',
 'offroad.racing.game',
 'game.revani.racemaxpro',
 'com.hutchgames.cccg',
 'com.oppanagames.car.simulator',
 'com.easygames.race',
 'com.creativemobile.nno',
 'com.frontrow.vlog',
 'com.camerasideas.trimmer',
 'com.snowcorp.vita',
 'com.nexstreaming.app.kinemasterfree',
 'com.camerasideas.instashot',
 'com.cyberlink.powerdirector.DRA140225_01',
 'com.videoeditorpro.android',
 'videoeditor.videomaker.videoeditorforyoutube',
 'com.wondershare.filmorago',
 'com.gopro.smarty',
 'ge.bebi.balloon.pop.game',
 'com.tocaboca.tocalifeworld',
 'com.rvappstudios.baby.toddler.kids.games.learning.activity',
 'com.mojang.minecraftpe',
 'com.rvappstudios.math.kids.counting',
 'com.pazugames.avatarworld',
 'com.logicappkids',
 'com.happytools.learning.kids.games',
 'com.kiloo.subwaysurf',
 'com.outfit7.mytalkingtom2',
 'com.nextwave.wcc3',
 'in.dreamgamestudios.games.sports.dreamcricket3d',
 'com.nautilus.RealCricket3D',
 'com.nautilus.realcricket',
 'com.miniclip.cricketleague',
 'cricketgames.hitwicket.strategy',
 'com.nextwave.wcc2',
 'sachin.cricket.game',
 'com.nautilus.realcricketchampionship',
 'com.jetplay.sachinsagacc',
 'com.skgames.trafficrider',
 'com.topfreegames.bikeracefreeworld',
 'com.weplay.motogp',
 'com.gravity.rider.balance.run.bike',
 'air.com.aceviral.motox3m',
 'com.ketchapp.rider.evolution.world.race.car.bike.flip',
 'mobi.gameguru.racingfevermoto',
 'com.turborilla.bike.racing.madskillsmotocross3',
 'com.tbegames.and.new_motor_racing',
 'com.turborilla.MadSkillsMotocross2']

In [6]:
len(appids)

50

In [8]:
for i in range(len(appids)):
    print(appids[i])

com.gameloft.android.ANMP.GloftA8HM
com.aim.racing
com.naturalmotion.customstreetracer2
com.ea.game.nfs14_row
offroad.racing.game
game.revani.racemaxpro
com.hutchgames.cccg
com.oppanagames.car.simulator
com.easygames.race
com.creativemobile.nno
com.frontrow.vlog
com.camerasideas.trimmer
com.snowcorp.vita
com.nexstreaming.app.kinemasterfree
com.camerasideas.instashot
com.cyberlink.powerdirector.DRA140225_01
com.videoeditorpro.android
videoeditor.videomaker.videoeditorforyoutube
com.wondershare.filmorago
com.gopro.smarty
ge.bebi.balloon.pop.game
com.tocaboca.tocalifeworld
com.rvappstudios.baby.toddler.kids.games.learning.activity
com.mojang.minecraftpe
com.rvappstudios.math.kids.counting
com.pazugames.avatarworld
com.logicappkids
com.happytools.learning.kids.games
com.kiloo.subwaysurf
com.outfit7.mytalkingtom2
com.nextwave.wcc3
in.dreamgamestudios.games.sports.dreamcricket3d
com.nautilus.RealCricket3D
com.nautilus.realcricket
com.miniclip.cricketleague
cricketgames.hitwicket.strategy
com.nextwave.wcc2
sachin.cricket.game
com.nautilus.realcricketchampionship
com.jetplay.sachinsagacc
com.skgames.trafficrider
com.topfreegames.bikeracefreeworld
com.weplay.motogp
com.gravity.rider.balance.run.bike
air.com.aceviral.motox3m
com.ketchapp.rider.evolution.world.race.car.bike.flip
mobi.gameguru.racingfevermoto
com.turborilla.bike.racing.madskillsmotocross3
com.tbegames.and.new_motor_racing
com.turborilla.MadSkillsMotocross2

In [10]:
final_data = []
for i in range(len(appids)):
    data = app(appids[i] , country = "in")
    final_data.append(data)

In [11]:
final_data

[{'title': 'Asphalt 8 - Car Racing Game',
  'description': "Part of Gameloft’s Asphalt franchise, Asphalt 8 is one of race car games offering an extensive collection of over 400+ licensed cars and motorbikes, delivering action-packed races across 75+ tracks. Immerse yourself in the thrilling world of high-speed racing as you jump into the driver's seat.\r\n\r\nExplore stunning scenarios and landscapes, ranging from the scorching Nevada Desert to the bustling streets of Tokyo. Compete against skilled racers, conquer exciting challenges, and engage in limited-time special racing events. Prepare your car for the ultimate test and unleash your drifting skills on the asphalt.\r\n\r\nLicensed luxury cars and motorcycles\r\nLuxury cars and motorcycles take center stage in Asphalt 8, with an impressive selection of top-tier vehicles from renowned manufacturers like Lamborghini, Bugatti, Porsche, and more. Experience the power of over 300 high-performance cars and motorcycles, alongside a wide variety of racing motorbikes. Customize and design your race cars and motorcycles to stand out from the crowd. Collect special-edition cars, explore diverse worlds and scenarios, all while perfecting your drifting technique.\r\n\r\nShow your racing style\r\nShowcase your unique racing style by unleashing your creativity and customizing your racer avatar. Mix and match clothes and accessories to craft a one-of-a-kind look that complements your car. Let your personality shine through as you dominate the racetrack.\r\n\r\nGet airborne with Asphalt 8\r\nPrepare for exhilarating gravity-defying action in Asphalt 8. Take your race to the skies as you hit ramps and perform breathtaking barrel rolls and 360° jumps. Compete against other racers or challenge yourself in single-player mode, executing daring mid-air maneuvers and stunts in your car or motorcycle to maximize your speed. Customize your controls and on-screen icons to suit your playstyle, ensuring victory in every race.\r\n\r\nEndless content for speed enthusiasts\r\nFuel your racing passion with a constant stream of fresh content. Experience regular updates, unlock powerful car upgrades, and dominate the competitive circuit. Explore seasons, engage in live events, and discover unique game modes. Compete in limited-time Cups to win valuable prizes, including early access to the latest cars and motorbikes.\r\n\r\nMultiplayer and single-player racing thrill\r\nImmerse yourself in thrilling multiplayer and single-player races. Join the multiplayer community, compete in the World Series, and challenge skilled opponents. Earn points, unlock prizes, and feel the adrenaline in limited-time racing events and racing passes. Fight for victory and savor the intensity of each race.\r\n\r\n_____________________________________________\r\nDon't forget to follow us on social media:\r\nDiscord: https://gmlft.co/A8-dscrd\r\nFacebook: https://gmlft.co/A8-Facebook\r\nTwitter: https://gmlft.co/A8-Twitter\r\nInstagram: https://gmlft.co/A8-Instagram\r\nYouTube: https://gmlft.co/A8-YouTube\r\n\r\nVisit our official site at http://gmlft.co/website_EN\r\nCheck out the new blog at http://gmlft.co/central\r\n\r\nThis app allows you to purchase virtual items within the app and may contain third-party advertisements that may redirect you to a third-party site.\r\n\r\nPrivacy Policy: http://www.gameloft.com/en/privacy-notice\r\nTerms of Use: http://www.gameloft.com/en/conditions-of-use\r\nEnd-User License Agreement: http://www.gameloft.com/en/eula",
  'descriptionHTML': 'Part of Gameloft’s Asphalt franchise, Asphalt 8 is one of race car games offering an extensive collection of over 400+ licensed cars and motorbikes, delivering action-packed races across 75+ tracks. Immerse yourself in the thrilling world of high-speed racing as you jump into the driver&#39;s seat.<br><br>Explore stunning scenarios and landscapes, ranging from the scorching Nevada Desert to the bustling streets of Tokyo. Compete against skilled racers, conquer exciting challenges, and engage in limited-time special racing events. Prepare your car for the ultimate test and unleash your drifting skills on the asphalt.<br><br>Licensed luxury cars and motorcycles<br>Luxury cars and motorcycles take center stage in Asphalt 8, with an impressive selection of top-tier vehicles from renowned manufacturers like Lamborghini, Bugatti, Porsche, and more. Experience the power of over 300 high-performance cars and motorcycles, alongside a wide variety of racing motorbikes. Customize and design your race cars and motorcycles to stand out from the crowd. Collect special-edition cars, explore diverse worlds and scenarios, all while perfecting your drifting technique.<br><br>Show your racing style<br>Showcase your unique racing style by unleashing your creativity and customizing your racer avatar. Mix and match clothes and accessories to craft a one-of-a-kind look that complements your car. Let your personality shine through as you dominate the racetrack.<br><br>Get airborne with Asphalt 8<br>Prepare for exhilarating gravity-defying action in Asphalt 8. Take your race to the skies as you hit ramps and perform breathtaking barrel rolls and 360° jumps. Compete against other racers or challenge yourself in single-player mode, executing daring mid-air maneuvers and stunts in your car or motorcycle to maximize your speed. Customize your controls and on-screen icons to suit your playstyle, ensuring victory in every race.<br><br>Endless content for speed enthusiasts<br>Fuel your racing passion with a constant stream of fresh content. Experience regular updates, unlock powerful car upgrades, and dominate the competitive circuit. Explore seasons, engage in live events, and discover unique game modes. Compete in limited-time Cups to win valuable prizes, including early access to the latest cars and motorbikes.<br><br>Multiplayer and single-player racing thrill<br>Immerse yourself in thrilling multiplayer and single-player races. Join the multiplayer community, compete in the World Series, and challenge skilled opponents. Earn points, unlock prizes, and feel the adrenaline in limited-time racing events and racing passes. Fight for victory and savor the intensity of each race.<br><br>_____________________________________________<br>Don&#39;t forget to follow us on social media:<br>Discord: https://gmlft.co/A8-dscrd<br>Facebook: https://gmlft.co/A8-Facebook<br>Twitter: https://gmlft.co/A8-Twitter<br>Instagram: https://gmlft.co/A8-Instagram<br>YouTube: https://gmlft.co/A8-YouTube<br><br>Visit our official site at http://gmlft.co/website_EN<br>Check out the new blog at http://gmlft.co/central<br><br>This app allows you to purchase virtual items within the app and may contain third-party advertisements that may redirect you to a third-party site.<br><br>Privacy Policy: http://www.gameloft.com/en/privacy-notice<br>Terms of Use: http://www.gameloft.com/en/conditions-of-use<br>End-User License Agreement: http://www.gameloft.com/en/eula',
  'summary': 'Experience multiplayer races with fast cars and motorcycles.',
  'installs': '500,000,000+',
  'minInstalls': 500000000,
  'realInstalls': 517606370,
  'score': 4.3038135,
  'ratings': 11766884,
  'reviews': 459031,
  'histogram': [1022569, 382553, 654743, 1644481, 8062513],
  'price': 0,
  'free': True,
  'currency': 'INR',
  'sale': False,
  'saleTime': None,
  'originalPrice': None,
  'saleText': None,
  'offersIAP': True,
  'inAppProductPrice': '₹9.00 - ₹12,900.00 per item',
  'developer': 'Gameloft SE',
  'developerId': '4826827787946964969',
  'developerEmail': 'android.support@gameloft.com',
  'developerWebsite': 'http://www.gameloft.com/',
  'developerAddress': None,
  'privacyPolicy': 'http://www.gameloft.com/privacy-notice/',
  'genre': 'Racing',
  'genreId': 'GAME_RACING',
  'categories': [{'name': 'Racing', 'id': 'GAME_RACING'},
   {'name': 'Car race', 'id': None},
   {'name': 'Multiplayer', 'id': None},
   {'name': 'Competitive multiplayer', 'id': None},
   {'name': 'Single player', 'id': None},
   {'name': 'Stylized', 'id': None},
   {'name': 'Vehicles', 'id': None},
   {'name': 'Sports car', 'id': None},
   {'name': 'Vehicles', 'id': None},
   {'name': 'Car', 'id': None},
   {'name': 'Offline', 'id': None}],
  'icon': 'https://play-lh.googleusercontent.com/y1J3-OrqJIlezTtaung2sPOnHY9wS2hdJh26ADkwcc3kdZy4DTGyv94IN_YRvdKy0y4',
  'headerImage': 'https://play-lh.googleusercontent.com/HuReVcmZu16_IpUUkZ6rHnsr1rAwp-BzREl0U2DQy531EbrTkx64MtT8_pwmFrRQdMj6EdsiyYtmxrHbc1HA',
  'screenshots': ['https://play-lh.googleusercontent.com/dhOFRTswUhXAiuaiM1kf2uDbZXJ6UBw9iznSBSlRr79N_9TAPNUfiAKzhnEbeYs_-Eg',
   'https://play-lh.googleusercontent.com/4V6OyD55nW9YOgwF7xfjxf-0k1BuYtuP2oMW-CDUC9LbRGbTk4R-0BkbpL2qAsxFxAU',
   'https://play-lh.googleusercontent.com/F7scKYPJ-kIxs4LKdg6JBiWxBBYIQ8fs3SCHfQX81ClYB66086xW0N3-7cLxfvqnK0_h',
   'https://play-lh.googleusercontent.com/OGEPXlrlYSauDab7VXkLFzHJ70zqLawU2UVdAbMbTNY3IbD4IlA7ZbL1zRX7FG7nkQ',
   'https://play-lh.googleusercontent.com/JFDsqaLFEOlTWB-fvVDsMy1Hs_RCdtm1Mf1MAaZ8lIwgpLI_El6oBwfW1TeDIehZSnY',
   'https://play-lh.googleusercontent.com/-Ui4cPAOlx7KfO5jh3p_lDVPg7wuFt3wkP_tO1-4FcKxP3dWPvs5FYcjWHuy1BU5oYhW',
   'https://play-lh.googleusercontent.com/lhLqVqzBCXiweqbg616HdV1pvJjRbNnuEUitMmVqZgpx-Jez0ZiF4EVxe1dOqhU8vVo',
   'https://play-lh.googleusercontent.com/XmbMTgg87IQD1IaXGgy-_JJXrqAzsYPV3luZAK969shWd15TsW80skv-lgAs_9E5MW-n',
   'https://play-lh.googleusercontent.com/Y-0u2sg4wiC1dufvxAe-AeCIIYyGMsfDYiY_iN_wIr1c8XnmPV9DwtrSx5UqTq1BzHx5',
   'https://play-lh.googleusercontent.com/rU70n-GdavdTI_c2kx3WsIM9eWbddIuNe1V_T-Sc4Uzi65h7JSmMa8T5Ky5yWjmDk0g',
   'https://play-lh.googleusercontent.com/qnL8SW-mPVQpL7AMS4Vq9nOaKMgdvOXv7yxWPzIWgNnZ6EbWSnxNRpYgd94p7D_dRSPV',
   'https://play-lh.googleusercontent.com/rTWU9lp3sP0FgchIO8aqe1PckQ2wru8hzNTVpKPavtGFgUYHZK656iMkcVMI2zk0CtY',
   'https://play-lh.googleusercontent.com/qxwwW2vqgFvjxfwOfeZjD4VwRMsh6DMs0WoWeGDysBajxUCmfikp2-fEhC7MvKKOAdE',
   'https://play-lh.googleusercontent.com/8QNur3GMp6D5_duHn7YwmNJ4xcvTF4KtTmJZHJk9QpmdLpsRX0tLlq0B-iyI0Cm7CGU',
   'https://play-lh.googleusercontent.com/XAz0UtKmXpJjMIj617Z7ysW3rDGrnwjmDDcOzBRAoiERK0q3n841pnVM5qQIE_lE_cyd',
   'https://play-lh.googleusercontent.com/JAsu9UvB4w57u4-CWp4SHC-V5szD8tAJHzIb9-UydD4_a2SEbJh5XxPZXZ93kKNpiQ',
   'https://play-lh.googleusercontent.com/TtPDj4Y2E6_c8Iw3cA78IU-M2vIm2TzOyLzBXLi5zmOwhodLK3X-jFZhkq2olho0z6pB',
   'https://play-lh.googleusercontent.com/gVEW3TvGxz5Yh-XvQAenQFWeV8tRy9Hnczuof4l1NgoQpi74pmMTAgJC-_cH3jtK4_Iu',
   'https://play-lh.googleusercontent.com/p9tHQILmoUXq1rHO9In15Z3qgxo3icB5zM0Rj5xItIBJA694_H8CDwrfu5PjiiL4jq8',
   'https://play-lh.googleusercontent.com/-RgSS-aEepaJlnXJVf8BmCeuc62Omm5XDiyMT1io3G-d2zKLiSlMzxz634WKqSgbllc',
   'https://play-lh.googleusercontent.com/FOLYXDiNwSmpp3BHmLQETyqsSsjwti6lQeLnPvwx1xSGO8IlDQqGAwrGAn0WfX13Znc',
   'https://play-lh.googleusercontent.com/v44_fgsitw6b51KV3ULwT2BKV0ymuK_oUNxIOwJmkJcpPaEWgvYai-xzq--FTu5EMeXg',
   'https://play-lh.googleusercontent.com/2xjkkve0YDNsJSSJgydpE3uF9cKBAiXl5RGsrSa5GRP4L1bmr-FkKqPqU9MXmexjfgw',
   'https://play-lh.googleusercontent.com/P5nmJ0Ed8RWhN1akPjoLO619WV3RGdl5wagBbyrCfgfSYnCMmcSr_LddMNZVIpxe',
   'https://play-lh.googleusercontent.com/OBE1PTjsmE6wIn7QTg77ZNAnXTZUkvIHfqp4op0dSu3CbufkdOCJvsbQbrmTsjpaX4Y',
   'https://play-lh.googleusercontent.com/QOwKekrLJ5I4I2k7HweaRpgJ3cgtv606BRsa_aFv1ezvPWqWEofvy-IahVFeRDJnW7tW',
   'https://play-lh.googleusercontent.com/AAUL7K-E7TnRVFmFOOGi6D-Mb8akBs8d36fPs6lfTbtrheEirlFO68kULZaEvbQV2uU',
   'https://play-lh.googleusercontent.com/eQ3t1TksD87LD3cM5h1laWPTvj8O5WLSaezKaBqD5wSeNlbENGVl8IqkHoXJQncKHHk',
   'https://play-lh.googleusercontent.com/2juywVLj21-LisDhImwsDaUyqoJYzPkOh3gju-gEwdiIcwkEQC5WBdehp1_m0se3NA',
   'https://play-lh.googleusercontent.com/F2iHjopAqEtwtCe7YWILBzTGqZNgXQhOCDWscxDKjY-OndbwlCJVZ4dfGkxbvehIrIs',
   'https://play-lh.googleusercontent.com/zviFGW2hDHh5qrnBvDGx05dhryz62Vx7xY5rbUlSHbCHifHXnXrAHB93qecr42IIBfk'],
  'video': 'https://www.youtube.com/embed/TEuZZB_zSOw?ps=play&vq=large&rel=0&autohide=1&showinfo=0',
  'videoImage': 'https://play-lh.googleusercontent.com/HuReVcmZu16_IpUUkZ6rHnsr1rAwp-BzREl0U2DQy531EbrTkx64MtT8_pwmFrRQdMj6EdsiyYtmxrHbc1HA',
  'contentRating': 'Rated for 7+',
  'contentRatingDescription': 'Mild Violence, Implied Violence',
  'adSupported': True,
  'containsAds': True,
  'released': 'Aug 20, 2013',
  'lastUpdatedOn': 'Aug 14, 2025',
  'updated': 1755169314,
  'version': '8.5.0j',
  'comments': [],
  'appId': 'com.gameloft.android.ANMP.GloftA8HM',
  'url': 'https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftA8HM&hl=en&gl=in'},
 {'title': 'Extreme Car Driving Simulator',
  'description': 'Extreme Car Driving Simulator is the open world car simulator since 2014, thanks to its advanced real physics engine\r\nEver wanted to try a sports car simulator? Now you can drive, drift and feel a racing sports car!\r\nBe a furious racer on a whole city for you. No need to brake because of traffic or racing other rival vehicles, so you can perform illegal stunt actions and run full speed without the police chasing you!\r\n\r\nDrifting fast and doing burnouts had never been so fun! Burn the asphalt of this open world city!\r\n\r\nGame Features\r\n\r\nMini game checkpoint mode\r\nDrive with traffic\r\nFull real HUD including revs, gear and speed\r\nABS, TC and ESP simulation. You can also turn them off!\r\nExplore a detailed open world environment\r\nRealistic car damage. Crash your car!\r\nAccurate physics\r\nControl your car with a steering wheel, accelerometer or arrows\r\nSeveral different cameras\r\nGamepad support',
  'descriptionHTML': 'Extreme Car Driving Simulator is the open world car simulator since 2014, thanks to its advanced real physics engine<br>Ever wanted to try a sports car simulator? Now you can drive, drift and feel a racing sports car!<br>Be a furious racer on a whole city for you. No need to brake because of traffic or racing other rival vehicles, so you can perform illegal stunt actions and run full speed without the police chasing you!<br><br>Drifting fast and doing burnouts had never been so fun! Burn the asphalt of this open world city!<br><br>Game Features<br><br>Mini game checkpoint mode<br>Drive with traffic<br>Full real HUD including revs, gear and speed<br>ABS, TC and ESP simulation. You can also turn them off!<br>Explore a detailed open world environment<br>Realistic car damage. Crash your car!<br>Accurate physics<br>Control your car with a steering wheel, accelerometer or arrows<br>Several different cameras<br>Gamepad support',
  'summary': 'The open world car driving simulator with the ultimate graphic updates',
  'installs': '500,000,000+',
  'minInstalls': 500000000,
  'realInstalls': 672462706,
  'score': 4.33161,
  'ratings': 4751175,
  'reviews': 294956,
  'histogram': [422505, 147580, 254005, 534822, 3392244],
  'price': 0,
  'free': True,
  'currency': 'INR',
  'sale': False,
  'saleTime': None,
  'originalPrice': None,
  'saleText': None,
  'offersIAP': True,
  'inAppProductPrice': '₹100.00 - ₹10,000.00 per item',
  'developer': 'AxesInMotion Racing',
  'developerId': '7842996855899014066',
  'developerEmail': 'support@axesinmotion.com',
  'developerWebsite': 'https://www.axesinmotion.com',
  'developerAddress': None,
  'privacyPolicy': 'https://www.axesinmotion.com/privacy',
  'genre': 'Racing',
  'genreId': 'GAME_RACING',
  'categories': [{'name': 'Simulation', 'id': 'GAME_SIMULATION'},
   {'name': 'Vehicle', 'id': None},
   {'name': 'Car sim', 'id': None},
   {'name': 'Casual', 'id': 'GAME_CASUAL'},
   {'name': 'Multiplayer', 'id': None},
   {'name': 'Competitive multiplayer', 'id': None},
   {'name': 'Single player', 'id': None},
   {'name': 'Stylized', 'id': None},
   {'name': 'Vehicles', 'id': None},
   {'name': 'Sports car', 'id': None},
   {'name': 'Vehicles', 'id': None},
   {'name': 'Car', 'id': None},
   {'name': 'Offline', 'id': None}],
  'icon': 'https://play-lh.googleusercontent.com/6NEtpPjWbslnt7WzHb4A1sYM6GiX_VdIhA6O9gAvJcf-GlmnEkfMQwPzAD7xTSLV_5M',
  'headerImage': 'https://play-lh.googleusercontent.com/9sGBPOY6IPIvja_L9MRMv-37e46sY_B_PXm5olQeUmLbzLR8mYkAW81XyA8pEsrS93E',
  'screenshots': ['https://play-lh.googleusercontent.com/8DDj07hiPNbnET4tZCc3lQrJ9orO8lwEKnhO8g9lbM-W19TQ_6s-y6TcoYfhQ6dFWUaL',
   'https://play-lh.googleusercontent.com/I12qN0oEVRsc9AXB8tp0w6A20AV99K1oNyhJa-OgjfdE1JcnKdcEtLTN4wIig18Auw',
   'https://play-lh.googleusercontent.com/s0Knivt2T37zNUAG6iXgiqf9OosUDyyjwAGFpN1HZyJpZUkLx3hx96oQO2HI4hivyA',
   'https://play-lh.googleusercontent.com/0n9vxQdSSnRp98EDRw4Ku-CS11SvZMgcS-qLyFARvyI3L61_Dcl5OvJ2S4B2NwB262Y',
   'https://play-lh.googleusercontent.com/wU-ScVCujYNPlUmJf35zpPyn9gK615CY9c4wAXn_jB68hXHlvaieasAsopzs1DUeIyXoIj3xcPu5NNYMSH1CrA',
   'https://play-lh.googleusercontent.com/xA8w2l5k1MnW_aFb4eHl-VnKXbQbWXoJOqrGrs6a1oeF62Kajg1lHOt6fnPehte1AhU',
   'https://play-lh.googleusercontent.com/ouIsBR0uG6-dpwlba3OuvCmxRJHR1audNQWAIxZmGb-mwhiITu-PKM9Te3KfsWKbd08',
   'https://play-lh.googleusercontent.com/0mEDutqSp5ZhiRg6riGMH75wvf7_S6l92jGJUfuxy_yKcR9hn62iKuG2Ol9tlMdljA',
   'https://play-lh.googleusercontent.com/KT7Z87ty0PlULI4JgqluMKG15f9cDzsoKueYl6uNPpJVwlGRrOtTlVKga2X-Ns85jRS3',
   'https://play-lh.googleusercontent.com/QwxvPvZTxXJ4Wxef0qeNjuPMivZ-1hKz4JiGGdCxplQPLg5sQEbTR0udf4sxkWtbp24',
   'https://play-lh.googleusercontent.com/VjmfI8Dl1iBUHs5brLqr3OyC6t4jg9w1_CBcCMBX4-1mQux4hLEkvabAR-wNBEv_rN8',
   'https://play-lh.googleusercontent.com/jex9s8WWiEXN_m7tIPusQk6PCwf81G3YKeOEXGVUM2crs_VXO_L4ddoZHgM6gA65Pms',
   'https://play-lh.googleusercontent.com/wU-ScVCujYNPlUmJf35zpPyn9gK615CY9c4wAXn_jB68hXHlvaieasAsopzs1DUeIyXoIj3xcPu5NNYMSH1CrA',
   'https://play-lh.googleusercontent.com/kA08hQB3nM9ul8X4ih3DgipY1PgwpxyJIpfm19grOYP7IKDuAmAnKgBN-xb6gxUyReQ',
   'https://play-lh.googleusercontent.com/U09WUE3IVoh6-VOy7CfiNVhfTAsKN5W0GutB42HWJKiO2aGcn-YjZ503D1zEI0HjOEI',
   'https://play-lh.googleusercontent.com/ZSqM4XIJyLwoC1GWrJmLakdd6w8HxklzVeTcrwW4RzCHTDk4J2XYrqEaN9_GWXSTTvA',
   'https://play-lh.googleusercontent.com/tqVldf7LtO-dWTQDnSDFOaG2K34rkT34CAmAL8X5RLoK86zOeYMJ3w7wlspjT4mbwg',
   'https://play-lh.googleusercontent.com/a0CiGVID2S3XwfD1YNC5f2ntGtFyt7YPwrLHABQqrBoaLFXawo9wCaxaT8kxFKoiaU_E',
   'https://play-lh.googleusercontent.com/eKE8NaGlVX6uYSlHSeYvReNiGLmr4rSq1Rjo1D792PbCFmYI0OXwD4EEL2ecJsOlOCc',
   'https://play-lh.googleusercontent.com/C1fgGrv9HbpNbz9wFQ_j15g3ttZUoh1rhfLquK9dWbbygcoOIr9sUoJcofrASnamIA',
   'https://play-lh.googleusercontent.com/xRNLquwTGgQULPbyIgGsMcDjOEXSM6XFSlWquFvl0nGUng7vuq5UmhHPsQfZbkShju2TOZojcz9wGII-nLmCDg',
   'https://play-lh.googleusercontent.com/YSR0QUbRnylmUHhN6F3NtTI5OzQcvmW5AGgL8sUbClRoqfu_GHA9DbvM0Ai0MmKg650',
   'https://play-lh.googleusercontent.com/EGcrbpLpAz3dNihgC0YAAhUNYYxnGLrjKtIgrft52tjMSuEW_wKhM5fXRgGTRDhX9Tw',
   'https://play-lh.googleusercontent.com/BcXJsZhO9DLwEsIIkZQh7h1j2VCRxExBsawbYaVjQ3dBBC3PJ4uB5yhUZfv3spMRvJ8',
   'https://play-lh.googleusercontent.com/AonmqzqiYnHPT5sgufzCQEnZMBTNs2LGRumFjpglIkRWox1jCxh4J9mLMs23vbfc8c8',
   'https://play-lh.googleusercontent.com/z3yurZYiV_7vmSeKMZ_1dCPWtZ8jhSUW5COx-9g21_8NUN1XIV5ynUWqY7OhrL_Mb4FE',
   'https://play-lh.googleusercontent.com/lc2kBvXfIGZXUmcncAF0MoK9DwL361Gn2StVnkFmYnjCVyeZqBVHFbKsucEPDYJAZcA',
   'https://play-lh.googleusercontent.com/o0CoellDaJRnRWzOSgzXef2xc-ryCVKT7oJ4m5zrTfXGgNY9smnPk11BU18uLPdFcyBn',
   'https://play-lh.googleusercontent.com/xRNLquwTGgQULPbyIgGsMcDjOEXSM6XFSlWquFvl0nGUng7vuq5UmhHPsQfZbkShju2TOZojcz9wGII-nLmCDg',
   'https://play-lh.googleusercontent.com/wC4CqFj0br-jMW5rT7rACU2OcbCRMki0qWV5i1cx9oL5dS37emMPgT4gEg6C2mlZ2A',
   'https://play-lh.googleusercontent.com/bsjzrCGFbzxeIlR7L1qAEioqNd9-Kxb9KS5CNU31xKg3bzZ-C7XuRF8JLNV8_TLVglI',
   'https://play-lh.googleusercontent.com/2R81Wwncsia6GaefAiPMl_MlAXGrrPShrX8KPIm-KreSAwLXbDp4E-Gi0WwUcCEIrrI'],

In [12]:
len(final_data)

50

      - title
      - installs
      - ratings
      - score
      - reviews
      - price
      - genre
      - url

In [13]:
final_data[0]["title"]

'Asphalt 8 - Car Racing Game'

In [14]:
final_data[0]["installs"]

'500,000,000+'

In [15]:
final_data[0]["ratings"]

11766884

In [16]:
final_data[0]["score"]

4.3038135

In [17]:
final_data[0]["reviews"]

459031

In [18]:
final_data[0]["price"]

0

In [19]:
final_data[0]["genre"]

'Racing'

In [20]:
final_data[0]["url"]

'https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftA8HM&hl=en&gl=in'

      - title
      - installs
      - ratings
      - score
      - reviews
      - price
      - genre
      - url

In [22]:
name = []
installs = []
ratings = []
score = []
reviews = []
price = []
genre = []
url = []

for i in range(len(final_data)):
    name.append(final_data[i]["title"])
    installs.append(final_data[i]["installs"])
    ratings.append(final_data[i]["ratings"])
    score.append(final_data[i]["score"])
    reviews.append(final_data[i]["reviews"])
    price.append(final_data[i]["price"])
    genre.append(final_data[i]["genre"])
    url.append(final_data[i]["url"])
else:
    print("Work Done")

Work Done

In [23]:
len(name)

50

In [24]:
name

['Asphalt 8 - Car Racing Game',
 'Extreme Car Driving Simulator',
 'CSR 2 Realistic Drag Racing',
 'Need for Speed™ No Limits',
 'Off Road 4x4 Driving Simulator',
 'Race Max Pro - Car Racing',
 'Top Drives - Car Race Battles',
 'Car Simulator 2',
 'Race Master 3D: Car Racing',
 'Nitro Nation: Car Racing Game',
 'VN - Video Editor & Maker',
 'YouCut - Video Editor & Maker',
 'VITA - Video Editor & Maker',
 'KineMaster - Video Editor',
 'Video Editor & Maker - InShot',
 'PowerDirector - Video Editor',
 'VivaCut - AI Video Editor',
 'Video Maker - Video.Guru',
 'Filmora - Video Editor & Maker',
 'GoPro Quik: Video Editor',
 'Balloon Pop Kids Learning Game',
 'Toca Boca World',
 'Kids Games: For Toddlers 3-5',
 'Minecraft: Dream it, Build it!',
 'Math Kids: Math Games For Kids',
 'Avatar World ®',
 'LogicLike: ABC & Math for kids',
 'Bebi: Baby Games for 2-4y kids',
 'Subway Surfers',
 'My Talking Tom 2',
 'World Cricket Championship 3',
 'Dream Cricket 2025',
 'Real Cricket™ 20',
 'Real Cricket™ 24',
 'Cricket League',
 'Hitwicket Cricket Game 2025',
 'World Cricket Championship 2',
 'Sachin Saga Pro Cricket Games',
 'Real Cricket Swipe',
 'Sachin Saga Cricket Champions',
 'Traffic Rider',
 'Bike Race：Motorcycle Games',
 "MotoGP Racing '23",
 'Gravity Rider: Space Bike Race',
 'Moto X3M Bike Race Game',
 'Rider Worlds - Neon Bike Races',
 'Racing Fever: Moto',
 'Mad Skills Motocross 3',
 'TopBike: Racing & Moto 3D Bike',
 'Mad Skills Motocross 2']

In [25]:
len(installs)

50

In [26]:
installs

['500,000,000+',
 '500,000,000+',
 '50,000,000+',
 '100,000,000+',
 '50,000,000+',
 '10,000,000+',
 '10,000,000+',
 '100,000,000+',
 '100,000,000+',
 '50,000,000+',
 '100,000,000+',
 '100,000,000+',
 '100,000,000+',
 '500,000,000+',
 '500,000,000+',
 '100,000,000+',
 '100,000,000+',
 '100,000,000+',
 '100,000,000+',
 '10,000,000+',
 '1,000,000+',
 '100,000,000+',
 '50,000,000+',
 '50,000,000+',
 '50,000,000+',
 '100,000,000+',
 '5,000,000+',
 '10,000,000+',
 '1,000,000,000+',
 '500,000,000+',
 '10,000,000+',
 '10,000,000+',
 '50,000,000+',
 '50,000,000+',
 '100,000,000+',
 '10,000,000+',
 '100,000,000+',
 '10,000,000+',
 '1,000,000+',
 '10,000,000+',
 '500,000,000+',
 '100,000,000+',
 '10,000,000+',
 '10,000,000+',
 '100,000,000+',
 '10,000,000+',
 '100,000,000+',
 '50,000,000+',
 '10,000,000+',
 '50,000,000+']

In [27]:
len(ratings)

50

In [28]:
ratings

[11766884,
 4751175,
 5202691,
 5230728,
 204971,
 502065,
 434417,
 1843746,
 3012981,
 1592430,
 4635465,
 8123765,
 911951,
 6004173,
 23158888,
 1729886,
 1416789,
 2984039,
 1121694,
 1044210,
 42808,
 6327186,
 47122,
 5453464,
 61650,
 4640101,
 55933,
 234293,
 42123155,
 6560422,
 478094,
 109331,
 1641743,
 626664,
 2965193,
 225093,
 3322377,
 48857,
 56642,
 516019,
 8811497,
 3113025,
 814069,
 112850,
 546500,
 68462,
 700996,
 109359,
 86278,
 471841]

In [29]:
len(score)

50

In [30]:
score

[4.3038135,
 4.33161,
 4.097079,
 4.0658584,
 4.141533,
 4.6215515,
 2.9281929,
 4.6432343,
 4.130198,
 3.6551158,
 4.6024537,
 4.7147503,
 4.421332,
 4.352142,
 4.722935,
 4.3754363,
 4.195514,
 4.608335,
 4.047585,
 4.5377293,
 4.564014,
 4.2281423,
 3.6920033,
 4.586931,
 3.877176,
 4.6284103,
 4.375,
 4.367169,
 4.399092,
 4.20365,
 4.141092,
 4.1894884,
 4.141972,
 4.3513746,
 4.557633,
 4.4614034,
 4.110651,
 4.2176843,
 4.4219975,
 3.932185,
 4.276027,
 4.065381,
 3.8987691,
 4.232107,
 4.266086,
 4.5,
 4.0162563,
 3.3314037,
 3.8906698,
 3.7268722]

In [31]:
reviews

[459031,
 294956,
 38074,
 211203,
 18941,
 10484,
 6670,
 100639,
 41171,
 16893,
 732375,
 293115,
 229043,
 666125,
 1327112,
 99000,
 15392,
 173780,
 87564,
 9199,
 1511,
 25642,
 1661,
 71203,
 2464,
 21003,
 207,
 18311,
 1718419,
 317861,
 134479,
 33366,
 541934,
 153081,
 339653,
 36248,
 1112469,
 13970,
 8405,
 196995,
 323414,
 99864,
 15793,
 14157,
 11243,
 313,
 63752,
 1283,
 4933,
 3723]

In [32]:
price

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 29.0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [33]:
genre

['Racing',
 'Racing',
 'Racing',
 'Racing',
 'Racing',
 'Racing',
 'Racing',
 'Simulation',
 'Racing',
 'Racing',
 'Video Players & Editors',
 'Video Players & Editors',
 'Video Players & Editors',
 'Video Players & Editors',
 'Photography',
 'Video Players & Editors',
 'Video Players & Editors',
 'Video Players & Editors',
 'Video Players & Editors',
 'Video Players & Editors',
 'Educational',
 'Educational',
 'Educational',
 'Arcade',
 'Educational',
 'Role Playing',
 'Educational',
 'Educational',
 'Arcade',
 'Casual',
 'Sports',
 'Sports',
 'Sports',
 'Sports',
 'Sports',
 'Sports',
 'Sports',
 'Sports',
 'Sports',
 'Sports',
 'Racing',
 'Racing',
 'Racing',
 'Racing',
 'Racing',
 'Arcade',
 'Racing',
 'Racing',
 'Racing',
 'Racing']

In [34]:
url

['https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftA8HM&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.aim.racing&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.naturalmotion.customstreetracer2&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.ea.game.nfs14_row&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=offroad.racing.game&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=game.revani.racemaxpro&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.hutchgames.cccg&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.oppanagames.car.simulator&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.easygames.race&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.creativemobile.nno&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.frontrow.vlog&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.camerasideas.trimmer&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.snowcorp.vita&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.nexstreaming.app.kinemasterfree&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.camerasideas.instashot&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.cyberlink.powerdirector.DRA140225_01&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.videoeditorpro.android&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=videoeditor.videomaker.videoeditorforyoutube&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.wondershare.filmorago&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.gopro.smarty&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=ge.bebi.balloon.pop.game&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.tocaboca.tocalifeworld&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.rvappstudios.baby.toddler.kids.games.learning.activity&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.mojang.minecraftpe&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.rvappstudios.math.kids.counting&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.pazugames.avatarworld&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.logicappkids&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.happytools.learning.kids.games&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.kiloo.subwaysurf&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.outfit7.mytalkingtom2&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.nextwave.wcc3&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=in.dreamgamestudios.games.sports.dreamcricket3d&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.nautilus.RealCricket3D&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.nautilus.realcricket&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.miniclip.cricketleague&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=cricketgames.hitwicket.strategy&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.nextwave.wcc2&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=sachin.cricket.game&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.nautilus.realcricketchampionship&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.jetplay.sachinsagacc&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.skgames.trafficrider&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.topfreegames.bikeracefreeworld&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.weplay.motogp&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.gravity.rider.balance.run.bike&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=air.com.aceviral.motox3m&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.ketchapp.rider.evolution.world.race.car.bike.flip&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=mobi.gameguru.racingfevermoto&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.turborilla.bike.racing.madskillsmotocross3&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.tbegames.and.new_motor_racing&hl=en&gl=in',
 'https://play.google.com/store/apps/details?id=com.turborilla.MadSkillsMotocross2&hl=en&gl=in']

In [51]:
import pandas as pd

In [52]:
data = pd.DataFrame({
    "Name" : name,
    "Installs" : installs,
    "Ratings" : ratings,
    "Score" : score,
    "Reviews" : reviews,
    "Price" : price,
    "Genre" : genre,
    "URL" : url
})

In [53]:
data

,Name,Installs,Ratings,Score,Reviews,Price,Genre,URL
0,Asphalt 8 - Car Racing Game,"500,000,000+",11766884,4.303814,459031,0.0,Racing,https://play.google.com/store/apps/details?id=...
1,Extreme Car Driving Simulator,"500,000,000+",4751175,4.331610,294956,0.0,Racing,https://play.google.com/store/apps/details?id=...
2,CSR 2 Realistic Drag Racing,"50,000,000+",5202691,4.097079,38074,0.0,Racing,https://play.google.com/store/apps/details?id=...
3,Need for Speed™ No Limits,"100,000,000+",5230728,4.065858,211203,0.0,Racing,https://play.google.com/store/apps/details?id=...
4,Off Road 4x4 Driving Simulator,"50,000,000+",204971,4.141533,18941,0.0,Racing,https://play.google.com/store/apps/details?id=...
5,Race Max Pro - Car Racing,"10,000,000+",502065,4.621551,10484,0.0,Racing,https://play.google.com/store/apps/details?id=...
6,Top Drives - Car Race Battles,"10,000,000+",434417,2.928193,6670,0.0,Racing,https://play.google.com/store/apps/details?id=...
7,Car Simulator 2,"100,000,000+",1843746,4.643234,100639,0.0,Simulation,https://play.google.com/store/apps/details?id=...
8,Race Master 3D: Car Racing,"100,000,000+",3012981,4.130198,41171,0.0,Racing,https://play.google.com/store/apps/details?id=...
9,Nitro Nation: Car Racing Game,"50,000,000+",1592430,3.655116,16893,0.0,Racing,https://play.google.com/store/apps/details?id=...
10,VN - Video Editor & Maker,"100,000,000+",4635465,4.602454,732375,0.0,Video Players & Editors,https://play.google.com/store/apps/details?id=...
11,YouCut - Video Editor & Maker,"100,000,000+",8123765,4.714750,293115,0.0,Video Players & Editors,https://play.google.com/store/apps/details?id=...
12,VITA - Video Editor & Maker,"100,000,000+",911951,4.421332,229043,0.0,Video Players & Editors,https://play.google.com/store/apps/details?id=...
13,KineMaster - Video Editor,"500,000,000+",6004173,4.352142,666125,0.0,Video Players & Editors,https://play.google.com/store/apps/details?id=...
14,Video Editor & Maker - InShot,"500,000,000+",23158888,4.722935,1327112,0.0,Photography,https://play.google.com/store/apps/details?id=...
15,PowerDirector - Video Editor,"100,000,000+",1729886,4.375436,99000,0.0,Video Players & Editors,https://play.google.com/store/apps/details?id=...
16,VivaCut - AI Video Editor,"100,000,000+",1416789,4.195514,15392,0.0,Video Players & Editors,https://play.google.com/store/apps/details?id=...
17,Video Maker - Video.Guru,"100,000,000+",2984039,4.608335,173780,0.0,Video Players & Editors,https://play.google.com/store/apps/details?id=...
18,Filmora - Video Editor & Maker,"100,000,000+",1121694,4.047585,87564,0.0,Video Players & Editors,https://play.google.com/store/apps/details?id=...
19,GoPro Quik: Video Editor,"10,000,000+",1044210,4.537729,9199,0.0,Video Players & Editors,https://play.google.com/store/apps/details?id=...
20,Balloon Pop Kids Learning Game,"1,000,000+",42808,4.564014,1511,0.0,Educational,https://play.google.com/store/apps/details?id=...
21,Toca Boca World,"100,000,000+",6327186,4.228142,25642,0.0,Educational,https://play.google.com/store/apps/details?id=...
22,Kids Games: For Toddlers 3-5,"50,000,000+",47122,3.692003,1661,0.0,Educational,https://play.google.com/store/apps/details?id=...
23,"Minecraft: Dream it, Build it!","50,000,000+",5453464,4.586931,71203,29.0,Arcade,https://play.google.com/store/apps/details?id=...
24,Math Kids: Math Games For Kids,"50,000,000+",61650,3.877176,2464,0.0,Educational,https://play.google.com/store/apps/details?id=...
25,Avatar World ®,"100,000,000+",4640101,4.628410,21003,0.0,Role Playing,https://play.google.com/store/apps/details?id=...
26,LogicLike: ABC & Math for kids,"5,000,000+",55933,4.375000,207,0.0,Educational,https://play.google.com/store/apps/details?id=...
27,Bebi: Baby Games for 2-4y kids,"10,000,000+",234293,4.367169,18311,0.0,Educational,https://play.google.com/store/apps/details?id=...
28,Subway Surfers,"1,000,000,000+",42123155,4.399092,1718419,0.0,Arcade,https://play.google.com/store/apps/details?id=...
29,My Talking Tom 2,"500,000,000+",6560422,4.203650,317861,0.0,Casual,https://play.google.com/store/apps/details?id=...
30,World Cricket Championship 3,"10,000,000+",478094,4.141092,134479,0.0,Sports,https://play.google.com/store/apps/details?id=...
31,Dream Cricket 2025,"10,000,000+",109331,4.189488,33366,0.0,Sports,https://play.google.com/store/apps/details?id=...
32,Real Cricket™ 20,"50,000,000+",1641743,4.141972,541934,0.0,Sports,https://play.google.com/store/apps/details?id=...
33,Real Cricket™ 24,"50,000,000+",626664,4.351375,153081,0.0,Sports,https://play.google.com/store/apps/details?id=...
34,Cricket League,"100,000,000+",2965193,4.557633,339653,0.0,Sports,https://play.google.com/store/apps/details?id=...
35,Hitwicket Cricket Game 2025,"10,000,000+",225093,4.461403,36248,0.0,Sports,https://play.google.com/store/apps/details?id=...
36,World Cricket Championship 2,"100,000,000+",3322377,4.110651,1112469,0.0,Sports,https://play.google.com/store/apps/details?id=...
37,Sachin Saga Pro Cricket Games,"10,000,000+",48857,4.217684,13970,0.0,Sports,https://play.google.com/store/apps/details?id=...
38,Real Cricket Swipe,"1,000,000+",56642,4.421997,8405,0.0,Sports,https://play.google.com/store/apps/details?id=...
39,Sachin Saga Cricket Champions,"10,000,000+",516019,3.932185,196995,0.0,Sports,https://play.google.com/store/apps/details?id=...
40,Traffic Rider,"500,000,000+",8811497,4.276027,323414,0.0,Racing,https://play.google.com/store/apps/details?id=...
41,Bike Race：Motorcycle Games,"100,000,000+",3113025,4.065381,99864,0.0,Racing,https://play.google.com/store/apps/details?id=...
42,MotoGP Racing '23,"10,000,000+",814069,3.898769,15793,0.0,Racing,https://play.google.com/store/apps/details?id=...
43,Gravity Rider: Space Bike Race,"10,000,000+",112850,4.232107,14157,0.0,Racing,https://play.google.com/store/apps/details?id=...
44,Moto X3M Bike Race Game,"100,000,000+",546500,4.266086,11243,0.0,Racing,https://play.google.com/store/apps/details?id=...
45,Rider Worlds - Neon Bike Races,"10,000,000+",68462,4.500000,313,0.0,Arcade,https://play.google.com/store/apps/details?id=...
46,Racing Fever: Moto,"100,000,000+",700996,4.016256,63752,0.0,Racing,https://play.google.com/store/apps/details?id=...
47,Mad Skills Motocross 3,"50,000,000+",109359,3.331404,1283,0.0,Racing,https://play.google.com/store/apps/details?id=...
48,TopBike: Racing & Moto 3D Bike,"10,000,000+",86278,3.890670,4933,0.0,Racing,https://play.google.com/store/apps/details?id=...
49,Mad Skills Motocross 2,"50,000,000+",471841,3.726872,3723,0.0,Racing,https://play.google.com/store/apps/details?id=...

In [54]:
data.head()

,Name,Installs,Ratings,Score,Reviews,Price,Genre,URL
0,Asphalt 8 - Car Racing Game,"500,000,000+",11766884,4.303814,459031,0.0,Racing,https://play.google.com/store/apps/details?id=...
1,Extreme Car Driving Simulator,"500,000,000+",4751175,4.331610,294956,0.0,Racing,https://play.google.com/store/apps/details?id=...
2,CSR 2 Realistic Drag Racing,"50,000,000+",5202691,4.097079,38074,0.0,Racing,https://play.google.com/store/apps/details?id=...
3,Need for Speed™ No Limits,"100,000,000+",5230728,4.065858,211203,0.0,Racing,https://play.google.com/store/apps/details?id=...
4,Off Road 4x4 Driving Simulator,"50,000,000+",204971,4.141533,18941,0.0,Racing,https://play.google.com/store/apps/details?id=...

In [55]:
data.tail()

,Name,Installs,Ratings,Score,Reviews,Price,Genre,URL
45,Rider Worlds - Neon Bike Races,"10,000,000+",68462,4.500000,313,0.0,Arcade,https://play.google.com/store/apps/details?id=...
46,Racing Fever: Moto,"100,000,000+",700996,4.016256,63752,0.0,Racing,https://play.google.com/store/apps/details?id=...
47,Mad Skills Motocross 3,"50,000,000+",109359,3.331404,1283,0.0,Racing,https://play.google.com/store/apps/details?id=...
48,TopBike: Racing & Moto 3D Bike,"10,000,000+",86278,3.890670,4933,0.0,Racing,https://play.google.com/store/apps/details?id=...
49,Mad Skills Motocross 2,"50,000,000+",471841,3.726872,3723,0.0,Racing,https://play.google.com/store/apps/details?id=...

In [56]:
data.describe()

            Ratings      Score       Reviews      Price
count  5.000000e+01  50.000000  5.000000e+01  50.000000
mean   3.520879e+06   4.222941  2.023625e+05   0.580000
std    6.865139e+06   0.350941  3.541582e+05   4.101219
min    4.280800e+04   2.928193  2.070000e+02   0.000000
25%    2.273930e+05   4.073664  1.192475e+04   0.000000
50%    1.082952e+06   4.249097  3.962250e+04   0.000000
75%    4.638942e+06   4.451552  2.245830e+05   0.000000
max    4.212316e+07   4.722935  1.718419e+06  29.000000

In [57]:
data[:10]

,Name,Installs,Ratings,Score,Reviews,Price,Genre,URL
0,Asphalt 8 - Car Racing Game,"500,000,000+",11766884,4.303814,459031,0.0,Racing,https://play.google.com/store/apps/details?id=...
1,Extreme Car Driving Simulator,"500,000,000+",4751175,4.331610,294956,0.0,Racing,https://play.google.com/store/apps/details?id=...
2,CSR 2 Realistic Drag Racing,"50,000,000+",5202691,4.097079,38074,0.0,Racing,https://play.google.com/store/apps/details?id=...
3,Need for Speed™ No Limits,"100,000,000+",5230728,4.065858,211203,0.0,Racing,https://play.google.com/store/apps/details?id=...
4,Off Road 4x4 Driving Simulator,"50,000,000+",204971,4.141533,18941,0.0,Racing,https://play.google.com/store/apps/details?id=...
5,Race Max Pro - Car Racing,"10,000,000+",502065,4.621551,10484,0.0,Racing,https://play.google.com/store/apps/details?id=...
6,Top Drives - Car Race Battles,"10,000,000+",434417,2.928193,6670,0.0,Racing,https://play.google.com/store/apps/details?id=...
7,Car Simulator 2,"100,000,000+",1843746,4.643234,100639,0.0,Simulation,https://play.google.com/store/apps/details?id=...
8,Race Master 3D: Car Racing,"100,000,000+",3012981,4.130198,41171,0.0,Racing,https://play.google.com/store/apps/details?id=...
9,Nitro Nation: Car Racing Game,"50,000,000+",1592430,3.655116,16893,0.0,Racing,https://play.google.com/store/apps/details?id=...

In [58]:
data.to_csv("data.csv")